### ISSUE TITLE
Messages being retroactively nack'd in confirm mode with queue limits

### ISSUE THREAD

**Issue by sbidin** [pika/pika#911] opened 2018-01-02 17:51 UTC
I run a single producer and consumer (both using `SelectConnection`), writing to and reading from a single queue whose maximum size has been limited:

```python
{
    'x-max-length': 10,
    'x-overflow': 'reject-publish'
}
```

Channels are configured with publisher confirms (confirm_delivery) and log the individual acks and nacks. Sometimes (about once in 50k messages), a nack will occur that contradicts a multi-ack immediately before it. The confirmation messages seem to have been reacted to in the wrong order. An example:

```
2018-01-02 18:31:56,763 - root - INFO - ack multi 3460 
2018-01-02 18:31:56,763 - root - INFO - nack multi 3459 
```

Messages up to tag 3460 are ack'd but then those up to 3459 are nack'd. This causes the nack'd messages to be lost (since they are never republished). Things would have worked fine had the messages been processed in the opposite (and correct) order.

Is there something obviously wrong I might be doing? Please let me know if I can provide you with any more information. I'm using pika 0.11.2 with RabbitMQ 3.7.1. The issue persists when using pika's master as well.

**Comment by lukebakken** [comment] 2018-01-02 19:13
Could you please provide the complete set of code you're using? That would make it faster and easier for me to reproduce. What version of Erlang are you using and on which operating system? Thanks!

**Comment by sbidin** [comment] 2018-01-03 10:20
I'm using Erlang 20.0 on an up-to-date Arch Linux.

I'll provide a minimal working code example today.

**Comment by sbidin** [comment] 2018-01-03 13:06
[Here's the code.](https://gist.github.com/sbidin/a9f4b9cbf46af04ed08071cdc0f3f80f) Run the same script twice, once for the consumer and once for the producer. Please let me know if there's any way I can help.

**Comment by lukebakken** [comment] 2018-01-03 14:52
Thanks, I'll check it out today.

**Comment by lukebakken** [comment] 2018-01-03 18:41
@sbidin - I have an environment set up and have run this a couple times. In order to determine if the `ack`/`nack` issue has happened, are you searching the output of the program? If so, could you modify the code to "keep track" and more verbosely indicate when this situation occurs? I'm assuming this situation only manifests when the consuming process is unable to keep up with the producer.

**Comment by sbidin** [comment] 2018-01-04 13:43
Yes, I'm searching the output to determine when it happens. I've updated [the script](https://gist.github.com/sbidin/a9f4b9cbf46af04ed08071cdc0f3f80f) to log such moments with a special message. It'll print out "got retroactive nack?" after every such bad confirmation.

As for not being able to keep up with the producer, I'm not sure about that. Note that the queue is limited to only 10 messages. The nacks in question are messages sent by the server to the producer, telling it that the queue has reached capacity.

Thanks for looking into this!

**Comment by lukebakken** [comment] 2018-01-09 19:18
Thanks for the updated script. I'm not seeing the `got retroactive nack` message in the output, however. Could you give me a few more details?

* Are you running the producer/consumer processes on the same machine as RabbitMQ? (I'm assuming so...)
* What version of Python are you using?
* What are your machine specs?

**Comment by sbidin** [comment] 2018-01-10 15:50
Absolutely:

* Yes, running both producer and consumer on the same machine.
* Using Python 3.6.4.
* What exactly are you interested in? [Hopefully this helps.](https://gist.github.com/sbidin/e5b331d5d248532ad8766dbbbf9c1275)

**Comment by lukebakken** [comment] 2018-01-10 15:52
Thanks, that's what I'm looking for. One last question - this isn't a cloud environment, right? I'm just trying to figure out what could be different between your environment and mine.

**Comment by sbidin** [comment] 2018-01-10 16:21
Nope, no cloud environment. This is my personal machine.

Again, thanks a lot for looking into this!

**Comment by lukebakken** [comment] 2018-01-31 21:26
Removing this from the [`1.0.0` milestone](https://github.com/pika/pika/milestone/8) as I still can't reproduce.

**Comment by vitaly-krugl** [comment] 2018-05-10 09:36
@sbidin, @lukebakken: I think I may have found a possible bug in [user code](https://gist.github.com/sbidin/a9f4b9cbf46af04ed08071cdc0f3f80f#file-rabbitmq_confirm-py-L155) that can explain this issue:

```python
    def _on_message_nack(self, tag_to: int, multiple: bool) -> None:
        tag_from = self.last_nack + 1 if multiple else tag_to
        ....
```

I think that the line `tag_from = self.last_nack + 1 if multiple else tag_to` should instead be
```python
tag_from = max(self.last_nack, self.last_ack) + 1 if multiple else tag_to
```
because the multi-nack would presumably apply to messages since the most recent ack or nack from the broker.

**Comment by lukebakken** [comment] 2018-05-10 13:17
@vitaly-krugl that makes sense to me. Since I can't reproduce it, I'll close it. @sbidin if you can try out the suggested code, that would be great.

**Closed by lukebakken** 2018-05-10 13:17 UTC

**Comment by vitaly-krugl** [comment] 2018-05-10 15:16
@lukebakken, since the queue is configured to Max out at 10, I suspect this
becomes reproducible when the consumer process is occasionally not keeping
up with the producer.

>
