### ISSUE TITLE
pika.BlockingConnection hangs when RabbitMQ server does not have free  file/socket descriptors.

### ISSUE THREAD

**Issue by ulyktey** [pika/pika#647] opened 2015-09-12 12:38 UTC
Hi,
I am trying to connect to RabbitMQ host/server and get situation when BlockingConnection hangs. This is happening if server does not have free file/socket descriptors. I hoped that pika raise some error but nothing happen. I use pika 0.10 and RabbitMQ 3.5.4. Do you know how  it resolve? Thanks.
![untitled-1](https://cloud.githubusercontent.com/assets/2356392/9831507/95b3bf08-5963-11e5-88a7-d320ffcd48bf.jpg)

> > > import pika
> > > credentials = pika.PlainCredentials('guest', 'guest')
> > > parameters = pika.ConnectionParameters(host='host', port=5672, credentials=credentials)
> > > conn = pika.BlockingConnection(parameters=parameters)

**Comment by vitaly-krugl** [comment] 2015-09-14 16:20
@ulyktey: please describe how to reproduce this scenario in RabbitMQ (out of free file/socket descriptors).

**Comment by ulyktey** [comment] 2015-09-14 17:13
This situation is happened when RabbitMQ server does not have free file/socket descriptors. Please a look on screenshot above. In this case BlockingConnection._adapter_connect can not finishe loop: while not self.is_open:
   self.process_data_events()

**Comment by vitaly-krugl** [comment] 2015-09-14 21:20
On my MacBookPro, this file is located at /usr/local/etc/rabbitmq/rabbitmq-env.conf. I'll give it a try after work.

**Comment by ulyktey** [comment] 2015-09-15 13:19
ok, thanks

**Comment by vitaly-krugl** [comment] 2015-09-18 23:35
@ulyktey: please reproduce the issue with `logging.basicConfig(level=logging.DEBUG)` and attach pika log output as a comment here. Thank you.

**Comment by ulyktey** [comment] 2015-09-19 16:55
My script:
  1 import pika
  2 import logging
  3
  4 logging.basicConfig(level=logging.DEBUG)
  5
  6 credentials = pika.PlainCredentials('guest', 'guest1')
  7 parameters = pika.ConnectionParameters(host='localhost', port=5672, credentials=credentials)
  8 conn = pika.BlockingConnection(parameters=parameters)

Pika raise an error after 40 seconds.
Example of pika log on DEBUG
python test_pika.py
DEBUG:pika.callback:Added: {'callback': <bound method BlockingConnection._on_connection_error of <pika.adapters.blocking_connection.BlockingConnection object at 0x2757b10>>, 'only': None, 'one_shot': False, 'arguments': None}
DEBUG:pika.callback:Added: {'callback': <bound method BlockingConnection._on_connection_start of <pika.adapters.blocking_connection.BlockingConnection object at 0x2757b10>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 1}
INFO:pika.adapters.base_connection:Connecting to 10.8.69.121:5672

ERROR:pika.adapters.base_connection:Socket Error on fd 3: 104
ERROR:pika.adapters.base_connection:Incompatible Protocol Versions
Traceback (most recent call last):
  File "test_pika.py", line 8, in <module>
    conn = pika.BlockingConnection(parameters=parameters)
  File "/usr/lib/python2.6/site-packages/pika/adapters/blocking_connection.py", line 130, in __init__
    super(BlockingConnection, self).__init__(parameters, None, False)
  File "/usr/lib/python2.6/site-packages/pika/adapters/base_connection.py", line 72, in __init__
    on_close_callback)
  File "/usr/lib/python2.6/site-packages/pika/connection.py", line 600, in __init__
    self.connect()
  File "/usr/lib/python2.6/site-packages/pika/adapters/blocking_connection.py", line 230, in connect
    error = self._adapter_connect()
  File "/usr/lib/python2.6/site-packages/pika/adapters/blocking_connection.py", line 309, in _adapter_connect
    self.process_data_events()
  File "/usr/lib/python2.6/site-packages/pika/adapters/blocking_connection.py", line 240, in process_data_events
    if self._handle_read():
  File "/usr/lib/python2.6/site-packages/pika/adapters/blocking_connection.py", line 348, in _handle_read
    super(BlockingConnection, self)._handle_read()
  File "/usr/lib/python2.6/site-packages/pika/adapters/base_connection.py", line 343, in _handle_read
    return self._handle_error(error)
  File "/usr/lib/python2.6/site-packages/pika/adapters/base_connection.py", line 302, in _handle_error
    self._handle_disconnect()
  File "/usr/lib/python2.6/site-packages/pika/adapters/base_connection.py", line 248, in _handle_disconnect
    self._adapter_disconnect()
  File "/usr/lib/python2.6/site-packages/pika/adapters/blocking_connection.py", line 318, in _adapter_disconnect
    self._check_state_on_disconnect()
  File "/usr/lib/python2.6/site-packages/pika/adapters/blocking_connection.py", line 368, in _check_state_on_disconnect
    super(BlockingConnection, self)._check_state_on_disconnect()
  File "/usr/lib/python2.6/site-packages/pika/adapters/base_connection.py", line 149, in _check_state_on_disconnect
    raise exceptions.IncompatibleProtocolError
pika.exceptions.IncompatibleProtocolError

**Comment by vitaly-krugl** [comment] 2015-09-21 06:16
@gmr: I am able to get pika.BlockingConnection() constructor to hang on Fedora running in VirtualBox with RabbitMQ 3.5.4 and `ulimit -n 100` in `/etc/rabbitmq/rabbitmq-env.conf`using both pika 0.9.14 and 0.10.0. On 0.10.0, it blocks in the call to `BlockingConnection._process_io_for_connection_setup()->_flush_output()->EPollPoller.poll()`, while waiting for the connection handshake to complete after the socket got connected.

This is a condition where RabbitMQ is intentionally under-resourced. Pika Connection class could potentially set a timeout at the beginning of the connection setup handshake and abort the connection setup if this timer fires before the connection setup completes. This intentional FD under-allocation seems somewhat of a malicious case. Thus, I am not sure whether this can happen with a normal configuration and whether pika needs to do anything about this case at all.

CC @ulyktey

**Comment by vitaly-krugl** [comment] 2015-09-21 06:34
I also followed up in https://groups.google.com/forum/#!topic/rabbitmq-users/OioSFq1veFQ

**Comment by vitaly-krugl** [comment] 2015-09-21 06:41
@gmr: I am inclined to write this off as invalid RabbitMQ configuration, based on Michael Klishin's comments in https://groups.google.com/forum/#!topic/rabbitmq-users/OioSFq1veFQ

**Comment by ulyktey** [comment] 2015-09-21 10:37
Hi guys,

I did small fix in code for version pika 0.9.14. I added "timeout" option in pika.BlockingConnection and added check in this loop:
while not self.is_open and time.time() > time.time() - timeout:
self.process_data_events()

This fix works for me, but it would be better when pika will contain addition timeout option.

Thanks,
Yurii

**Comment by gst** [comment] 2015-10-09 20:52
@vitaly-krugl 

You say this is a malicious case, and I tend to agree with you, but malicious cases are not impossible cases..  shit happens, Murphy's law you know :)

So I agree with @ulyktey, his proposed solution (or something like that) seems to be what needs to be done.. / what's missing against this specific case.. imo.

nb: I've been testing pika these last 2 days and it's the kind of case that I also want to test/check and make sure that pika is safe/reliable/good against.

**Comment by vitaly-krugl** [comment] 2015-10-09 20:54
@gst, I've considered it further and agree with your assessment.

**Comment by gst** [comment] 2015-10-21 19:44
problem confirmed on my side.

**Comment by vitaly-krugl** [comment] 2016-01-12 22:00
Also, please see this discussion: https://groups.google.com/d/msg/rabbitmq-users/OioSFq1veFQ/L1iHPX4JGQAJ "`rabbitmqctl stop` hangs if RabbitMQ is out of FDs"

**Comment by vitaly-krugl** [comment] 2018-04-06 14:48
@lukebakken, this is one of the issues that is being addressed by my refactoring PR #1002. Should I re-assign this issue to myself?

**Closed** 2018-04-26 14:59 UTC
