### ISSUE TITLE
IncompatibleProtocolError when using pika with a transparent proxy

### ISSUE THREAD

**Issue by brucardoso2** [pika/pika#552] opened 2015-04-24 17:27 UTC
I got a squid running as a transparent proxy on the same machine of the software running pika.
"curl" works as expected, without any proxy setting (that's the whole point of using a transparent proxy).
python requests work as well.

This is what happens when trying to do a BlockingConnection.
```
Traceback (most recent call last):
File "/home/bruno/.virtualenvs/project/local/lib/python2.7/site-packages/mymodule/messenger.py", line 128, in _create_connection
    Messenger_connection = pika.BlockingConnection(parameters)
  File "/home/bruno/.virtualenvs/project/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 130, in __init__
    super(BlockingConnection, self).__init__(parameters, None, False)
  File "/home/bruno/.virtualenvs/project/local/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 72, in __init__
    on_close_callback)
  File "/home/bruno/.virtualenvs/project/local/lib/python2.7/site-packages/pika/connection.py", line 600, in __init__
    self.connect()
  File "/home/bruno/.virtualenvs/project/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 230, in connect
    error = self._adapter_connect()
  File "/home/bruno/.virtualenvs/project/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 309, in _adapter_connect
    self.process_data_events()
  File "/home/bruno/.virtualenvs/project/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 240, in process_data_events
    if self._handle_read():
  File "/home/bruno/.virtualenvs/project/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 348, in _handle_read
    super(BlockingConnection, self)._handle_read()
  File "/home/bruno/.virtualenvs/project/local/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 348, in _handle_read
    return self._handle_disconnect()
  File "/home/bruno/.virtualenvs/project/local/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 248, in _handle_disconnect
    self._adapter_disconnect()
  File "/home/bruno/.virtualenvs/project/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 318, in _adapter_disconnect
    self._check_state_on_disconnect()
  File "/home/bruno/.virtualenvs/project/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 368, in _check_state_on_disconnect
    super(BlockingConnection, self)._check_state_on_disconnect()
  File "/home/bruno/.virtualenvs/project/local/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 149, in _check_state_on_disconnect
    raise exceptions.IncompatibleProtocolError
IncompatibleProtocolError
```

Another thing I tried was opening a socket and it worked (passing throught the transparent proxy as well).
```python
import socket
s = socket.socket()
s.connect('<myip>', 5672)
```

**Comment by gmr** [comment] 2015-04-25 00:11
I would seem that it's not a totally transparent proxy or something else is going on between squid and your AMQP connection. IncompatibleProtocolError is raised during the initial connection stage and the client is disconnected by the remote end.

**Comment by brucardoso2** [comment] 2015-04-27 19:49
@gmr thanks for your response.
What makes me think that it could be related to the AMQP protocol is the fact that all HTTP requests work flawlessly.
I'll try to check what's happening on the rabbit end.

**Comment by gmr** [comment] 2015-04-27 20:20
You might want to try with haproxy. Last I checked, Squid was primarily a caching HTTP proxy and not protocol agnostic. This may have changed, of course.

**Comment by brucardoso2** [comment] 2015-04-27 21:35
Passing the proxy explicitly to the python application works, but with the transparent proxy it doesn't.
Checking with wireshark I could see that pika is using AMQP over HTTP (although it could be something from my side that is doing it)... I'll try to isolate the environment from any proxy to check what does pika actually does.

**Comment by gmr** [comment] 2015-04-29 00:48
Sounds like Squid is acting like an HTTP proxy and not a TCP/IP proxy. Closing this out since it's not a Pika issue.

**Closed by gmr** 2015-04-29 00:48 UTC

**Comment by jan1206** [comment] 2016-10-13 14:14
Looks like this was an issue with the code that tried to determine the cause of a connection failure and subsequently wouldn't propagate the reasons to the caller.

This has been fixed for me on the master branch:
https://github.com/pika/pika/commit/43936088e1183ec5902f2ba2992c902e87f5460b

**Comment by vitaly-krugl** [comment] 2016-10-24 23:10
@jan1206, thanks for the update!
