### ISSUE TITLE
python3 nonblocking socket

### ISSUE THREAD

**Issue by tazgithubmaster** [pika/pika#1082] opened 2018-06-21 10:52 UTC
I'm on debian streatch with pika 0.11 and python 3.5.3. I wrote a simple blocking publisher to send larger messages (max 10MB) over the wire. At it's core it breaks down to:
<pre>
with open(args.inputfile,"rb") as fd:
    body = fd.read()
    con=pika.BlockingConnection(parameters)
    ch=con.channel()
    ch.basic_publish(exchange=args.exchange,
                     routing_key=args.routingkey,
                     properties=props,
                     body=body)
</pre>
I was able to send small messages (about 20KB in size) but as soon as I tried to send larger Messages i got

``
pika.exceptions.ChannelClosed: Already closed: <Channel number=1 CLOSED conn=<SelectConnection CLOSED socket=None params=<ConnectionParameters host=amqp.taz.de port=5673 virtual_host=spielwiese ssl=True>>>
``

i could figure out a workaround by monkeypatching 

``pika.adapters.base_connection.BaseConnection._adapter_connect``

and setting:
<pre>
        if not error:
            # Make the socket non-blocking after the connect
            self.socket.setblocking(True)
</pre>

I had no issues with the same code when running python2.7.

**Comment by lukebakken** [comment] 2018-06-21 13:17
Hello! Please help us help you out.

* You say "larger Messages" but then fail to say just how much more large. At what size does this issue appear?
* Could you please provide all of your code, or at least a minimum reproducer that works out-of-the-box? Based on the very small and incomplete code snippet you provide I suspect you may be trying to re-use a connection or channel instance or are somehow not closing them correctly. But, without seeing more, I would be guessing which is not productive.
* What AMQP broker are you using?
* If RabbitMQ, what version and what version of Erlang?
* What operating system for your application and for your broker?
* Do you have any custom broker configuration?

Setting the socket to blocking is not the correct fix if there is in fact an issue.

I will keep this issue open for 24 hours to wait for a response.

**Comment by tazgithubmaster** [comment] 2018-06-21 13:44
* You say "larger Messages" but then fail to say just how much more large. At what size does this issue appear?

without the change i could only send 20KB messages. Increasing it to 200KB i got the problem.

* Could you please provide all of your code, or at least a minimum reproducer that works out-of-the-box? Based on the very small and incomplete code snippet you provide I suspect you may be trying to re-use a connection or channel instance or are somehow not closing them correctly. But, without seeing more, I would be guessing which is not productive.

<pre>
#!/usr/bin/env python3

import pika
from pika import ConnectionParameters
from pika.credentials import ExternalCredentials
from ssl import CERT_REQUIRED



ssl_options = dict(
    certfile = "amqp/amqp.crt",
    keyfile = "amqp/amqp.key",
    ca_certs = "amqp/cacert.crt",
    cert_reqs = CERT_REQUIRED )


parameters=ConnectionParameters(
    host = "amqp.taz.de",
    port = 5673,
    virtual_host = "spielwiese",
    credentials = ExternalCredentials(),
    ssl = True,
    ssl_options = ssl_options)

props = pika.BasicProperties(delivery_mode = 2)


with open("foo","rb") as fd:
    body = fd.read()
    print(len(body))
    con=pika.BlockingConnection(parameters)
    ch=con.channel()
    ch.basic_publish(exchange="spielwiese",
                     routing_key="spielroute",
                     properties=props,
                     body=body)

ch.close()
con.close()
</pre>
#!/usr/bin/env python3

import pika
from pika import ConnectionParameters
from pika.credentials import ExternalCredentials
from ssl import CERT_REQUIRED

ssl_options = dict(
    certfile = "amqp/amqp.crt",
    keyfile = "amqp/amqp.key",
    ca_certs = "amqp/cacert.crt",
    cert_reqs = CERT_REQUIRED )

parameters=ConnectionParameters(
    host = "amqp.taz.de",
    port = 5673,
    virtual_host = "spielwiese",
    credentials = ExternalCredentials(),
    ssl = True,
    ssl_options = ssl_options)

props = pika.BasicProperties(delivery_mode = 2)


with open("foo","rb") as fd:
    body = fd.read()
    print(len(body))
    con=pika.BlockingConnection(parameters)
    ch=con.channel()
    ch.basic_publish(exchange="spielwiese",
                     routing_key="spielroute",
                     properties=props,
                     body=body)

ch.close()
con.close()
</pre>

* What AMQP broker are you using?
* If RabbitMQ, what version and what version of Erlang?
the problem happens with rabbitmq 3.4.3-1 (Erlang R15B01) and with rabbitmq 3.6.15-1 (Erlang/OTP 19 [erts-8.2.1] )

* What operating system for your application and for your broker?
Problem happens on debian stretch and on arch-linux

* Do you have any custom broker configuration
yes, we use client certificates for authentification. when disable ssl i see ``pika.exceptions.ChannelClosed: Already closed: <Channel number=1 CLOSED conn=<SelectConnection CLOSED socket=None params=<ConnectionParameters host=amqp.taz.de port=5673 virtual_host=spielwiese ssl=True>>>`` if ssl is enabled i get 
<pre>

dd if=/dev/urandom of=foo bs=200k count=1
1+0 records in
1+0 records out
204800 bytes (205 kB, 200 KiB) copied, 0.00198611 s, 103 MB/s
[ak@bounty src]$ ./min.py
204800
Traceback (most recent call last):
  File "./min.py", line 36, in <module>
    body=body)
  File "/home/ak/.local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 2077, in basic_publish
    mandatory, immediate)
  File "/home/ak/.local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 2164, in publish
    self._flush_output()
  File "/home/ak/.local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1250, in _flush_output
    *waiters)
  File "/home/ak/.local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 474, in _flush_output
    result.reason_text)
pika.exceptions.ConnectionClosed: (-1, "SSLWantWriteError(3, 'The operation did not complete (write) (_ssl.c:2130)')")
</pre>

**Comment by lukebakken** [comment] 2018-06-21 14:08
Thank you very much, I will see if I can reproduce this.

**Comment by tazgithubmaster** [comment] 2018-06-21 14:13
thanks for the help. Setting the connection into blocking is only a workaround I'm aware of that but i lack the skill to solve the problem an other way :)

**Comment by lukebakken** [comment] 2018-06-21 14:37
@tazgithubmaster could you please share your entire RabbitMQ configuration? I can use my own SSL certs. Thanks.

**Comment by tazgithubmaster** [comment] 2018-06-21 14:48
rabbitmq 3.4 on debian wheezy
<pre>
#cat /etc/rabbitmq/rabbitmq.config 
[
  {
    rabbit, [
      { ssl_allow_poodle_attack, true},
      { cluster_nodes, {['rabbit@havelock.taz.de','rabbit@drumknott.taz.de'], disc}},
      { auth_mechanisms, ['PLAIN', 'AMQPLAIN', 'EXTERNAL'] },
      { ssl_cert_login_from, common_name },
      { loopback_users, [ "apache-loopback", <<"guest">> ] },
      { tcp_listeners, [ { "127.0.0.1",5672 } ]},
      { reverse_dns_lookups, true },
      { heartbeat, 30 },
      { tcp_listen_options, [binary,
                     {packet, raw},
                     {reuseaddr, true},
                     {backlog, 128},
                     {nodelay, true},
                     {exit_on_close, false},
                     {keepalive, true}]},
      { ssl_listeners, [ 5673]},
      { ssl_options, [
        { cacertfile,"/etc/rabbitmq/ssl/cacert.crt" },
        { certfile,"/etc/rabbitmq/ssl/drumknott-amqp.crt" },
        { keyfile,"/etc/rabbitmq/ssl/drumknott-amqp.key" },
        { verify,verify_peer },
        { fail_if_no_peer_cert,true },
        { depth, 1} ]
      }
    ]
  },
  {
    rabbitmq_management, [
      {  listener, [
        { port, 15672 },
        { ssl, true },
        { ssl_opts, [
          { cacertfile, "/etc/rabbitmq/ssl/cacert.crt" },
          { certfile,   "/etc/rabbitmq/ssl/drumknott-amqp.crt" },
          { keyfile,    "/etc/rabbitmq/ssl/drumknott-amqp.key" }
        ]}
     ]}
  ]}

].
</pre>

**Comment by lukebakken** [comment] 2018-06-21 15:21
Well, I have tried to reproduce this locally using RabbitMQ `3.6.16`, Erlang `19.3`, Pika `0.11.0` and Python `3.5.4` without any luck. I have tried with SSL enabled (client cert auth just as you have done), and without SSL.

Notice that I am using slightly newer versions of both RabbitMQ and Erlang. I know that there are changes to Erlang between version 19 and 19.3 that could affect you. Or, you could upgrade to the latest version in the 20.X release series (https://www.rabbitmq.com/install-debian.html)

We need to determine if this is due to TLS/SSL in your environment or not. Could you please change your test script to *not* use SSL and to connect to port `5672`? Then, re-run your test to see if you get the error.

Also, please note that Pika `0.12.0` is available. I doubt that upgrading will address this, but that is another consideration.

**Comment by shinji-s** [comment] 2018-06-21 15:32
Forgive me for chipping in to hazard a wild guess. Is there chance network latency/bandwidth is involved here?

**Comment by tazgithubmaster** [comment] 2018-06-21 15:40
i did setup an ssh-tunnel with ``ssh -L 5672:localhost:5672 havelock.taz.de`` to one of the nodes and used
<pre>
parameters=ConnectionParameters(
    host = "localhost",
    port = 5672,
    virtual_host = "spielwiese")
</pre>
I didn't get any error for filesizes upto 200MB (didn't try larger files)

* Forgive me for chipping in to hazard a wild guess. Is there chance network latency/bandwidth is involved here?

i don't think so - the same script (min.py with ssl) is working with python2 and 200MB files
<pre>
[ak@bounty src]$ python2 ./min.py 
209715200
[ak@bounty src]$ python3 ./min.py 
209715200
Traceback (most recent call last):
  File "./min.py", line 36, in <module>
    body=body)
  File "/home/ak/.local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 2077, in basic_publish
    mandatory, immediate)
  File "/home/ak/.local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 2164, in publish
    self._flush_output()
  File "/home/ak/.local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1250, in _flush_output
    *waiters)
  File "/home/ak/.local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 474, in _flush_output
    result.reason_text)
pika.exceptions.ConnectionClosed: (-1, "SSLWantWriteError(3, 'The operation did not complete (write) (_ssl.c:2130)')")
</pre>

**Comment by lukebakken** [comment] 2018-06-21 15:42
@tazgithubmaster you mention using Python `3.5.3` but that last stack trace indicates Python `3.6.X` (`/home/ak/.local/lib/python3.6/...`). Could you please run `python --version` as well as `pip list` in that environment? Thanks.

**Comment by tazgithubmaster** [comment] 2018-06-21 15:44
sure - it's my devel machine
<pre>
[ak@bounty src]$ python --version
Python 3.6.5
[ak@bounty src]$ python2 --version
Python 2.7.15
[ak@bounty src]$ pip list
Package                      Version  
---------------------------- ---------
aiodns                       1.1.1    
ansible                      2.5.4    
appdirs                      1.4.3    
asn1crypto                   0.24.0   
backcall                     0.1.0    
bcrypt                       3.1.4    
Beaker                       1.10.0   
blessings                    1.6.1    
bpython                      0.17.1   
Brlapi                       0.6.7    
btrfsutil                    1.0.0    
CacheControl                 0.12.5   
catfish                      1.4.5    
cffi                         1.11.5   
chardet                      3.0.4    
click                        6.7      
colorama                     0.3.9    
configobj                    5.0.6    
cryptography                 2.2.2    
cupshelpers                  1.0      
curtsies                     0.3.0    
cycler                       0.10.0   
Cython                       0.28.3   
decorator                    4.3.0    
distlib                      0.2.7    
distro                       1.3.0    
docutils                     0.14     
elasticsearch                5.1.0    
entrypoints                  0.2.3    
Flask                        1.0.2    
gajim                        1.0.3    
greenlet                     0.4.13   
gufw                         18.4.0   
html5lib                     1.0.1    
idna                         2.6      
imutils                      0.4.5    
iotop                        0.6      
ipython                      6.3.1    
ipython-genutils             0.1.0    
isc                          2.0      
itsdangerous                 0.24     
jedi                         0.12.0   
jeepney                      0.3.1    
Jinja2                       2.10     
keyring                      12.2.1   
lensfun                      0.3.2    
lightdm-gtk-greeter-settings 1.2.2    
lockfile                     0.12.2   
louis                        3.5.0    
Mako                         1.0.7    
MarkupSafe                   1.0      
matplotlib                   2.1.1    
msgpack                      0.5.6    
mysql-connector-python       8.0.11   
nbxmpp                       0.6.6    
networkx                     2.0      
npyscreen                    4.10.5   
numpy                        1.13.3   
packaging                    17.1     
pacman-mirrors               4.10.1   
pandas                       0.23.0   
paramiko                     2.4.1    
parso                        0.2.1    
pexpect                      4.6.0    
pickleshare                  0.7.4    
pika                         0.11.2   
Pillow                       5.0.0    
pip                          10.0.1   
ply                          3.11     
progress                     1.3      
prompt-toolkit               1.0.15   
psutil                       5.4.6    
ptyprocess                   0.5.2    
pyasn1                       0.3.7    
pyasn1-modules               0.1.5    
PyBluez                      0.22     
pycairo                      1.17.0   
pycares                      2.3.0    
pycparser                    2.18     
pycrypto                     2.6.1    
pycups                       1.9.73   
pycurl                       7.43.0.2 
Pygments                     2.2.0    
pygobject                    3.28.3   
PyNaCl                       1.2.1    
pyOpenSSL                    18.0.0   
pyparsing                    2.2.0    
pyparted                     3.11.1   
python-daemon                2.1.2    
python-dateutil              2.6.1    
python-libtorrent            1.1.7    
pytoml                       0.1.16   
pytz                         2017.3   
PyWavelets                   0.5.2    
pyxdg                        0.26     
PyYAML                       3.12     
ranger-fm                    1.9.1    
Recoll                       1.0      
requests                     2.18.4   
retrying                     1.3.3    
scikit-image                 0.13.1   
scipy                        1.0.0    
SecretStorage                3.0.1    
setuptools                   39.2.0   
simplegeneric                0.8.1    
six                          1.11.0   
sleekxmpp                    1.3.3    
team                         1.0      
traitlets                    4.3.2    
ufw                          0.35     
urllib3                      1.23     
virtualenv                   15.1.0   
wcwidth                      0.1.7    
webencodings                 0.5.1    
Werkzeug                     0.14.1   
xmltodict                    0.11.0   
youtube-dl                   2018.5.18
[ak@bounty src]$ pip2 list
Package                            Version
---------------------------------- -------
appdirs                            1.4.3  
asn1crypto                         0.24.0 
backports.shutil-get-terminal-size 1.0.0  
bcrypt                             3.1.4  
Beaker                             1.10.0 
CacheControl                       0.12.5 
cffi                               1.11.5 
chardet                            3.0.4  
colorama                           0.3.9  
cryptography                       2.2.2  
decorator                          4.3.0  
distlib                            0.2.7  
distro                             1.3.0  
dnet                               1.12   
docutils                           0.14   
duplicity                          0.7.17 
ecdsa                              0.13   
enum34                             1.1.6  
fasteners                          0.14.1 
funcsigs                           1.0.2  
gunicorn                           19.0.0 
html5lib                           1.0.1  
idna                               2.6    
ipaddress                          1.0.22 
ipython                            5.6.0  
ipython-genutils                   0.1.0  
Jinja2                             2.10   
lockfile                           0.12.2 
louis                              3.5.0  
Mako                               1.0.7  
MarkupSafe                         1.0    
monotonic                          1.5    
msgpack                            0.5.6  
mutagen                            1.40.0 
MySQL-python                       1.2.5  
nbxmpp                             0.6.6  
netifaces                          0.10.7 
netsnmp-python                     1.0a1  
packaging                          17.1   
paramiko                           2.4.1  
path.py                            8.2.1  
pathlib                            1.0.1  
pexpect                            4.6.0  
pickleshare                        0.7.4  
pika                               0.11.2 
pip                                10.0.1 
ply                                3.11   
progress                           1.3    
prompt-toolkit                     1.0.15 
psutil                             5.4.6  
ptyprocess                         0.5.2  
pyasn1                             0.4.2  
pyasn1-modules                     0.2.1  
PyBluez                            0.22   
pycairo                            1.17.0 
pycparser                          2.18   
pycrypto                           2.6.1  
Pygments                           2.2.0  
pygobject                          3.28.3 
PyNaCl                             1.2.1  
pyOpenSSL                          18.0.0 
pyparsing                          2.2.0  
python-daemon                      2.1.2  
python-ldap                        3.1.0  
python-libtorrent                  1.1.7  
python-musicbrainz                 0.0.0  
pytoml                             0.1.16 
pyxdg                              0.26   
PyYAML                             3.12   
requests                           2.18.4 
retrying                           1.3.3  
setuptools                         39.2.0 
simplegeneric                      0.8.1  
six                                1.11.0 
team                               1.0    
terminator                         1.91   
traitlets                          4.3.2  
urllib3                            1.23   
wcwidth                            0.1.7  
webencodings                       0.5.1  
zenmap                             7.70   
</pre>

**Comment by tazgithubmaster** [comment] 2018-06-21 16:02
mhhh i just installed pika 0.12 and it looks like this is fixing the issue.

**Comment by lukebakken** [comment] 2018-06-21 16:03
That's kind of surprising, but I'll leave it at that. Thanks for following up.

**Closed by lukebakken** 2018-06-21 16:03 UTC
Labels: Pending Investigation

**Comment by michaelklishin** [comment] 2018-06-21 17:01
@tazgithubmaster please [upgrade](http://www.rabbitmq.com/upgrade.html) to RabbitMQ 3.7.6 ASAP. 3.5.x has been out of support for at least a year now. You are *many* [releases behind](http://www.rabbitmq.com/changelog.html).
