### ISSUE TITLE
Connection unexpectedly stuck when consuming.

### ISSUE THREAD

**Issue by mosquito** [pika/pika#875] opened 2017-09-07 15:46 UTC
Hi there. I'm an author of `aio-pika` library. Few days ago @eldardamari create an issue [#54](https://github.com/mosquito/aio-pika/issues/54).

The consuming unexpectedly stops, after that rabbitmq kills the connection after heartbeat timeout.

```
10.248.24.41: =ERROR REPORT==== 7-Sep-2017::14:51:05 ===
10.248.24.41: closing AMQP connection <0.26023.456> (10.248.24.27:37536 -> 10.248.24.41:5672):
10.248.24.41: missed heartbeats from client, timeout: 60s
```

After some investigation I trying to switch to the `pika-0.10` and it helped.

Now I reverted pika-0.10 to the requirements.

**Comment by lukebakken** [comment] 2017-09-07 16:21
@mosquito @eldardamari

Could you please provide a complete set of code that reproduces this issue? That would speed up diagnosis and a resolution. Thanks!

**Comment by lukebakken** [comment] 2017-10-10 19:53
@mosquito @eldardamari - I will close this issue but please re-open it if you can provide code to reproduce.

**Comment by jbfondo** [comment] 2017-10-24 10:47
Exactly this issue happened to me recently. 
I'll try to post some code when i'm be able to reproduce it with a simple snippet.

Scenario:
- Several processes pubish in queue1.
- ProcessX listen from queue1, does some stuff and publish to queue2.
- ProcessX use a Threadpool to execute the function that process every message received. Just after this call, ProcessX acks this message (channel.basic_ack).
- The function that process the message, at the end, publish another message in queue2.

When using Pika 0.10.0 all work fine.
When I upgrade to pika 0.11.0 the issue opened by @mosquito  happened.

Solution1: Remove threadpool and process the message in the same thread/process
Solution2: Remove ack. I don't need ack messages.

**Comment by mosquito** [comment] 2017-10-24 11:08
@jbfondo can you provide simple script for reproduce this bug. If you could do it,
it should be exclude possible bugs in aio-pika. Pure-implementation (without any wrapper) should be better.

**Comment by jbfondo** [comment] 2017-10-24 17:24
I modified the asynchronous_consumer_example according to my last post.
If you let it run for a while consuming messages sent by the asynchronous_publisher_example, you can see, in a variable amount of time (maybe some minutes), that the consumer stops consuming until rabbitMQ server closes the connection.

The modified lines are marked by a comment "# +++++"


[asynchronous_consumer_example_modified.zip](https://github.com/pika/pika/files/1411772/asynchronous_consumer_example_modified.zip)

**Comment by decaz** [comment] 2018-01-08 13:03
@mosquito is this issue should be reopened? Is something need to be done from the `aio-pika` side to resolve such an issue or it's fully depends on `pika`?

**Comment by mosquito** [comment] 2018-01-08 13:59
@decaz I have no any tests which might reproduce it, but when version `0.10` has been frozen the problem was disappear.

**Comment by decaz** [comment] 2018-01-08 16:32
@mosquito you mean that reverting to `0.10` helped? Or there is no problem now and `aio-pika` can depend on `0.11`?

**Comment by lukebakken** [comment] 2018-01-08 23:59
@jbfondo thanks for the script, I will give it a try.

**Comment by finetuned89** [comment] 2018-02-02 15:33
Is there any progress on this? I have a situation where I need both aio-pika and pika==0.11. Is there something I can do to help?

**Comment by lukebakken** [comment] 2018-02-05 20:55
@jbfondo - you absolutely can't do what you're doing in that code. Channels are not thread safe.

I am going to do more research into mosquito/aio-pika#54, though nobody has provided code to reproduce this issue.

**Closed by lukebakken** 2018-02-05 20:55 UTC
Labels: Needs More Info

**Comment by lukebakken** [comment] 2018-03-13 13:48
@alfredodeza I don't see how that error is similar to what else is reported here. If you can provide a runnable code sample that I can use to reproduce this, please do so and open a new issue. The Pika maintainers do so on their free time so anything that can help us out is much appreciated.

**Comment by alfredodeza** [comment] 2018-03-13 15:30
@lukebakken apologies, got completely confused, I came from issue #881 and assumed this was related. Should've read the comments more thoroughly.

Will try to get a standalone/vanilla way to reproduce this. In the meantime, the removal of `acks` on every message has made this issue go away for us. Thanks again for helping out

**Comment by lukebakken** [comment] 2018-03-13 15:32
It's no problem! Thanks for clarifying and a standalone app will help me out immensely to fix the issue since I won't have to spend time guessing how to reproduce it.
