### ISSUE TITLE
BlockingConnection.close() hangs randomly if .consume was called before (with no_ack=True)

### ISSUE THREAD

**Issue by mishas** [pika/pika#743] opened 2016-04-25 16:27 UTC
I couldn't reproduce the code in a simpler way, so I have nothing to show for it, but in our (large) project, we see that blocking_connection.close() sometimes hangs for quiet a while.

In our setup we have a few (blocking) channels on which we do .consume (to get a generator()), and call next() on those generators from time to time.
The setup is single threaded, thus Issue #661 is not relevant for us.

Running with a debugger (pdb) we could pinpoint the problem to the _flush_output method of blocking_connection (see trace in the end).

Looking at the [comment on line 1600 of blocking_connection.py](https://github.com/pika/pika/blob/0.10.0/pika/adapters/blocking_connection.py#L1600), it looks like this code should only run if no_ack=False (which is not our case). Maybe that is the problem?

Thank you for your help,
and thanks for a wonderful open source project!

TRACE:
```
  [ ... ]
  File ".../pika/adapters/blocking_connection.py", line 1860, in cancel
    self.basic_cancel(self._queue_consumer_generator.consumer_tag)
  File ".../pika/adapters/blocking_connection.py", line 1612, in basic_cancel
    lambda: consumer_tag not in self._impl._consumers)
  File ".../pika/adapters/blocking_connection.py", line 1174, in _flush_output
    *waiters)
  File ".../pika/adapters/blocking_connection.py", line 420, in _flush_output
    result.reason_text)
```

**Comment by vitaly-krugl** [comment] 2016-04-25 19:25
Please post the following:

1. Operating System where pika was used
2. pika version
3. rabbitmq version
4. DEBUG-level log from pika for the affected period
5. rabbitmq log for the affected period

**Comment by vitaly-krugl** [comment] 2016-04-25 19:29
Also, you say "sometimes hangs for quiet a while". Does it eventually complete or does it hang forever?

**Comment by vitaly-krugl** [comment] 2016-04-25 19:31
In your traceback, `_flush_output` is waiting for the output buffer to be flushed and for `Basic.CancelOk` response from rabbitmq.

**Comment by mishas** [comment] 2016-04-26 06:45
Forgot to mention, very important note:
We have a context manager, where __enter__() creates the BlockingConnection and the channels, and the __exit__() calls BlockingConnection.stop(). It seems to fail only when there's an exception in the with block (but not always).

Operating System where pika was used: Mac/Ubuntu14.04/Debian8
pika version (or whether you're using pika from pika master branch): latest 0.10.0
rabbitmq version: 3.6.1 (Erlang 18.2)
DEBUG-level log from pika for the affected period: attached in the end.
rabbitmq log for the affected period: attached in the end.

About hanging for quiet a while:
Sometimes it finishes normally after a minute or two,
Sometimes it fails on timeout of heartbeat (as in the log in the bottom),
Sometimes it doesn't finish until I kill it manually.

About pipes being clogged: In my tests, I only send one message that makes the system stop (the handle function throws an intentional exception, which makes the with block exit, which calls stop). So - there should be no more than at most 1 message unprocessed.
I tried canceling and then closing each connection one by one, and the same happens. It seems to get stuck on "cancel" of one of the connections (not necessarily the first one).
(Actually the traceback above is from just such a test).

IMPORTANT NOTE:
I might have made a huge mistake! As I said, the code is very complex, and it uses threads in some areas. I just noticed that it actually does one of the consumes in a separate thread. It might be the case that if that thread still consumes, we get the problem.
Sorry for wasting your time :(.

Pika DEBUG log:
"""
I0426 06:33:15.443935 15553 pika/adapters/blocking_connection.py:616] Closing connection (200): Normal shutdown
I0426 06:33:15.444247 15553 pika/adapters/blocking_connection.py:1330] Channel.close(200, Normal shutdown)
D0426 06:33:15.444429 15553 pika/callback.py:164] Added: {'callback': <bound method _CallbackResult.signal_once of <pika.adapters.blocking_connection._CallbackResult object at 0x1030c8348>>, 'only': None, 'calls': 1, 'one_shot': True, 'arguments': None}
I0426 06:33:15.444664 15553 pika/channel.py:422] Channel.close(200, Normal shutdown)
D0426 06:33:15.444913 15553 pika/channel.py:1130] Adding in on_synchronous_complete callback
D0426 06:33:15.445104 15553 pika/callback.py:164] Added: {'callback': <bound method Channel._on_synchronous_complete of <pika.channel.Channel object at 0x101ec1be0>>, 'only': None, 'calls': 1, 'one_shot': True, 'arguments': None}
D0426 06:33:15.445281 15553 pika/channel.py:1135] Adding passed in callback
D0426 06:33:15.445432 15553 pika/callback.py:164] Added: {'callback': <bound method Channel._on_closeok of <pika.channel.Channel object at 0x101ec1be0>>, 'only': None, 'calls': 1, 'one_shot': True, 'arguments': None}
D0426 06:33:15.446360 15553 pika/callback.py:220] Processing 1:Channel.CloseOk
D0426 06:33:15.446560 15553 pika/callback.py:404] Processing use of oneshot callback
D0426 06:33:15.446718 15553 pika/callback.py:406] 0 registered uses left
D0426 06:33:15.446897 15553 pika/callback.py:269] Removing callback #0: {'callback': <bound method _CallbackResult.signal_once of <pika.adapters.blocking_connection._CallbackResult object at 0x1030c8348>>, 'only': None, 'calls': 0, 'one_shot': True, 'arguments': None}
D0426 06:33:15.447071 15553 pika/callback.py:404] Processing use of oneshot callback
D0426 06:33:15.447218 15553 pika/callback.py:406] 0 registered uses left
D0426 06:33:15.447385 15553 pika/callback.py:269] Removing callback #0: {'callback': <bound method Channel._on_synchronous_complete of <pika.channel.Channel object at 0x101ec1be0>>, 'only': None, 'calls': 0, 'one_shot': True, 'arguments': None}
D0426 06:33:15.447595 15553 pika/callback.py:404] Processing use of oneshot callback
D0426 06:33:15.447769 15553 pika/callback.py:406] 0 registered uses left
D0426 06:33:15.447985 15553 pika/callback.py:269] Removing callback #0: {'callback': <bound method Channel._on_closeok of <pika.channel.Channel object at 0x101ec1be0>>, 'only': None, 'calls': 0, 'one_shot': True, 'arguments': None}
D0426 06:33:15.448245 15553 pika/callback.py:234] Calling <bound method _CallbackResult.signal_once of <pika.adapters.blocking_connection._CallbackResult object at 0x1030c8348>> for "1:Channel.CloseOk"
D0426 06:33:15.448503 15553 pika/callback.py:234] Calling <bound method Channel._on_synchronous_complete of <pika.channel.Channel object at 0x101ec1be0>> for "1:Channel.CloseOk"
D0426 06:33:15.448688 15553 pika/channel.py:1088] 0 blocked frames
D0426 06:33:15.448974 15553 pika/callback.py:234] Calling <bound method Channel._on_closeok of <pika.channel.Channel object at 0x101ec1be0>> for "1:Channel.CloseOk"
D0426 06:33:15.449196 15553 pika/callback.py:220] Processing 1:_on_channel_cleanup
D0426 06:33:15.449373 15553 pika/callback.py:404] Processing use of oneshot callback
D0426 06:33:15.449587 15553 pika/callback.py:406] 0 registered uses left
D0426 06:33:15.449807 15553 pika/callback.py:269] Removing callback #0: {'callback': <bound method SelectConnection._on_channel_cleanup of <pika.adapters.select_connection.SelectConnection object at 0x101ec17f0>>, 'only': <pika.channel.Channel object at 0x101ec1be0>, 'calls': 0, 'one_shot': True, 'arguments': None}
D0426 06:33:15.450010 15553 pika/callback.py:234] Calling <bound method SelectConnection._on_channel_cleanup of <pika.adapters.select_connection.SelectConnection object at 0x101ec17f0>> for "1:_on_channel_cleanup"
D0426 06:33:15.450160 15553 pika/connection.py:1203] Removed channel 1
D0426 06:33:15.450367 15553 pika/callback.py:181] Clearing out '1' from the stack
I0426 06:33:20.450986 15553 pika/adapters/blocking_connection.py:1330] Channel.close(200, Normal shutdown)
D0426 06:33:20.451329 15553 pika/adapters/blocking_connection.py:1288] Cancelling 1 consumers
D0426 06:33:20.451611 15553 pika/callback.py:164] Added: {'callback': <bound method _CallbackResult.signal_once of <pika.adapters.blocking_connection._CallbackResult object at 0x101ef2708>>, 'only': None, 'calls': 1, 'one_shot': True, 'arguments': None}
D0426 06:33:20.451971 15553 pika/channel.py:1130] Adding in on_synchronous_complete callback
D0426 06:33:20.452234 15553 pika/callback.py:164] Added: {'callback': <bound method Channel._on_synchronous_complete of <pika.channel.Channel object at 0x101ee2860>>, 'only': None, 'calls': 1, 'one_shot': True, 'arguments': {'consumer_tag': 'ctag2.a2b3fcbb38d0445fb0f6dfbb849d06a6'}}
D0426 06:33:20.452481 15553 pika/channel.py:1135] Adding passed in callback
D0426 06:33:20.452662 15553 pika/callback.py:164] Added: {'callback': <bound method Channel._on_cancelok of <pika.channel.Channel object at 0x101ee2860>>, 'only': None, 'calls': 1, 'one_shot': True, 'arguments': {'consumer_tag': 'ctag2.a2b3fcbb38d0445fb0f6dfbb849d06a6'}}
D0426 06:33:20.453696 15553 pika/callback.py:220] Processing 2:Basic.CancelOk
D0426 06:33:20.453924 15553 pika/callback.py:404] Processing use of oneshot callback 
D0426 06:33:20.454105 15553 pika/callback.py:406] 0 registered uses left
D0426 06:33:20.454314 15553 pika/callback.py:269] Removing callback #0: {'callback': <bound method _CallbackResult.signal_once of <pika.adapters.blocking_connection._CallbackResult object at 0x101ef2708>>, 'only': None, 'calls': 0, 'one_shot': True, 'arguments': None}
D0426 06:33:20.454524 15553 pika/callback.py:404] Processing use of oneshot callback 
D0426 06:33:20.454696 15553 pika/callback.py:406] 0 registered uses left
D0426 06:33:20.454895 15553 pika/callback.py:350] Comparing {'consumer_tag': 'ctag2.a2b3fcbb38d0445fb0f6dfbb849d06a6'} to {'consumer_tag': 'ctag2.a2b3fcbb38d0445fb0f6dfbb849d06a6'}
D0426 06:33:20.455216 15553 pika/callback.py:269] Removing callback #0: {'callback': <bound method Channel._on_synchronous_complete of <pika.channel.Channel object at 0x101ee2860>>, 'only': None, 'calls': 0, 'one_shot': True, 'arguments': {'consumer_tag': 'ctag2.a2b3fcbb38d0445fb0f6dfbb849d06a6'}}
D0426 06:33:20.455432 15553 pika/callback.py:404] Processing use of oneshot callback
D0426 06:33:20.455602 15553 pika/callback.py:406] 0 registered uses left
D0426 06:33:20.455795 15553 pika/callback.py:350] Comparing {'consumer_tag': 'ctag2.a2b3fcbb38d0445fb0f6dfbb849d06a6'} to {'consumer_tag': 'ctag2.a2b3fcbb38d0445fb0f6dfbb849d06a6'}
D0426 06:33:20.455980 15553 pika/callback.py:269] Removing callback #0: {'callback': <bound method Channel._on_cancelok of <pika.channel.Channel object at 0x101ee2860>>, 'only': None, 'calls': 0, 'one_shot': True, 'arguments': {'consumer_tag': 'ctag2.a2b3fcbb38d0445fb0f6dfbb849d06a6'}}
D0426 06:33:20.456148 15553 pika/callback.py:234] Calling <bound method _CallbackResult.signal_once of <pika.adapters.blocking_connection._CallbackResult object at 0x101ef2708>> for "2:Basic.CancelOk"
D0426 06:33:20.456301 15553 pika/callback.py:234] Calling <bound method Channel._on_synchronous_complete of <pika.channel.Channel object at 0x101ee2860>> for "2:Basic.CancelOk"
D0426 06:33:20.456448 15553 pika/channel.py:1088] 0 blocked frames
D0426 06:33:20.456596 15553 pika/callback.py:234] Calling <bound method Channel._on_cancelok of <pika.channel.Channel object at 0x101ee2860>> for "2:Basic.CancelOk"
D0426 06:33:25.458982 15553 pika/callback.py:164] Added: {'callback': <bound method _CallbackResult.signal_once of <pika.adapters.blocking_connection._CallbackResult object at 0x1030bfa48>>, 'only': None, 'calls': 1, 'one_shot': True, 'arguments': None}
I0426 06:33:25.459490 15553 pika/channel.py:422] Channel.close(200, Normal shutdown)
D0426 06:33:25.459808 15553 pika/channel.py:1130] Adding in on_synchronous_complete callback
D0426 06:33:25.460108 15553 pika/callback.py:164] Added: {'callback': <bound method Channel._on_synchronous_complete of <pika.channel.Channel object at 0x101ee2860>>, 'only': None, 'calls': 1, 'one_shot': True, 'arguments': None}
D0426 06:33:25.460507 15553 pika/channel.py:1135] Adding passed in callback
D0426 06:33:25.460766 15553 pika/callback.py:164] Added: {'callback': <bound method Channel._on_closeok of <pika.channel.Channel object at 0x101ee2860>>, 'only': None, 'calls': 1, 'one_shot': True, 'arguments': None}
D0426 06:33:25.461918 15553 pika/callback.py:220] Processing 2:Channel.CloseOk
D0426 06:33:25.462225 15553 pika/callback.py:404] Processing use of oneshot callback
D0426 06:33:25.462506 15553 pika/callback.py:406] 0 registered uses left
D0426 06:33:25.462714 15553 pika/callback.py:269] Removing callback #0: {'callback': <bound method _CallbackResult.signal_once of <pika.adapters.blocking_connection._CallbackResult object at 0x1030bfa48>>, 'only': None, 'calls': 0, 'one_shot': True, 'arguments': None}
D0426 06:33:25.462896 15553 pika/callback.py:404] Processing use of oneshot callback
D0426 06:33:25.463044 15553 pika/callback.py:406] 0 registered uses left
D0426 06:33:25.463214 15553 pika/callback.py:269] Removing callback #0: {'callback': <bound method Channel._on_synchronous_complete of <pika.channel.Channel object at 0x101ee2860>>, 'only': None, 'calls': 0, 'one_shot': True, 'arguments': None}
D0426 06:33:25.463384 15553 pika/callback.py:404] Processing use of oneshot callback
D0426 06:33:25.463526 15553 pika/callback.py:406] 0 registered uses left
D0426 06:33:25.463692 15553 pika/callback.py:269] Removing callback #0: {'callback': <bound method Channel._on_closeok of <pika.channel.Channel object at 0x101ee2860>>, 'only': None, 'calls': 0, 'one_shot': True, 'arguments': None}
D0426 06:33:25.463856 15553 pika/callback.py:234] Calling <bound method _CallbackResult.signal_once of <pika.adapters.blocking_connection._CallbackResult object at 0x1030bfa48>> for "2:Channel.CloseOk"
D0426 06:33:25.464008 15553 pika/callback.py:234] Calling <bound method Channel._on_synchronous_complete of <pika.channel.Channel object at 0x101ee2860>> for "2:Channel.CloseOk"
D0426 06:33:25.464154 15553 pika/channel.py:1088] 0 blocked frames
D0426 06:33:25.464302 15553 pika/callback.py:234] Calling <bound method Channel._on_closeok of <pika.channel.Channel object at 0x101ee2860>> for "2:Channel.CloseOk"
D0426 06:33:25.464479 15553 pika/callback.py:220] Processing 2:_on_channel_cleanup
D0426 06:33:25.464627 15553 pika/callback.py:404] Processing use of oneshot callback
D0426 06:33:25.464767 15553 pika/callback.py:406] 0 registered uses left
D0426 06:33:25.464916 15553 pika/callback.py:269] Removing callback #0: {'callback': <bound method SelectConnection._on_channel_cleanup of <pika.adapters.select_connection.SelectConnection object at 0x101ec17f0>>, 'only': <pika.channel.Channel object at 0x101ee2860>, 'calls': 0, 'one_shot': True, 'arguments': None}
D0426 06:33:25.465069 15553 pika/callback.py:234] Calling <bound method SelectConnection._on_channel_cleanup of <pika.adapters.select_connection.SelectConnection object at 0x101ec17f0>> for "2:_on_channel_cleanup"
D0426 06:33:25.465206 15553 pika/connection.py:1203] Removed channel 2
D0426 06:33:25.465352 15553 pika/callback.py:181] Clearing out '2' from the stack
I0426 06:33:30.466241 15553 pika/connection.py:731] Closing connection (200): Normal shutdown
D0426 06:33:30.466788 15553 pika/callback.py:164] Added: {'callback': <bound method SelectConnection._on_connection_closed of <pika.adapters.select_connection.SelectConnection object at 0x101ec17f0>>, 'only': None, 'calls': 1, 'one_shot': True, 'arguments': None}
D0426 06:33:30.470046 15553 pika/callback.py:220] Processing 0:Connection.CloseOk
D0426 06:33:30.470364 15553 pika/callback.py:404] Processing use of oneshot callback
D0426 06:33:30.470584 15553 pika/callback.py:406] 0 registered uses left
D0426 06:33:30.470823 15553 pika/callback.py:269] Removing callback #0: {'callback': <bound method SelectConnection._on_connection_closed of <pika.adapters.select_connection.SelectConnection object at 0x101ec17f0>>, 'only': None, 'calls': 0, 'one_shot': True, 'arguments': None}
D0426 06:33:30.471062 15553 pika/callback.py:234] Calling <bound method SelectConnection._on_connection_closed of <pika.adapters.select_connection.SelectConnection object at 0x101ec17f0>> for "0:Connection.CloseOk"
D0426 06:33:30.471275 15553 pika/heartbeat.py:108] Removing timeout for next heartbeat interval
D0426 06:33:30.471660 15553 pika/callback.py:164] Added: {'callback': <bound method SelectConnection._on_connection_start of <pika.adapters.select_connection.SelectConnection object at 0x101ec17f0>>, 'only': None, 'calls': 1, 'one_shot': True, 'arguments': None}
W0426 06:33:30.471938 15553 pika/connection.py:1360] Disconnected from RabbitMQ at 192.168.99.100:5672 (200): Normal shutdown
D0426 06:33:30.472259 15553 pika/callback.py:220] Processing 0:_on_connection_closed
D0426 06:33:30.472552 15553 pika/callback.py:234] Calling <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x101ec9708>> for "0:_on_connection_closed"
I0426 06:33:30.472954 15553 pika/adapters/blocking_connection.py:428] Connection closed; result=BlockingConnection__OnClosedArgs(connection=<pika.adapters.select_connection.SelectConnection object at 0x101ec17f0>, reason_code=200, reason_text='Normal shutdown')
"""

Traceback after when I did Ctrl+C after ~10 minutes:
"""
Traceback (most recent call last):
  [ ... ]
  File ".../rmq/connector.py", line 68, in close
    self._connection.close()
  File "pika/adapters/blocking_connection.py", line 629, in close
    self._flush_output(self._closed_result.is_ready)
  File "pika/adapters/blocking_connection.py", line 410, in _flush_output
    self._impl.ioloop.poll()
  File "pika/adapters/select_connection.py", line 515, in poll
    self.get_next_deadline())
KeyboardInterrupt
"""

RabbitMQ log:
"""
=INFO REPORT==== 26-Apr-2016::06:33:10 ===
accepting AMQP connection <0.2404.0> (192.168.99.1:51158 -> 172.22.0.2:5672)

=INFO REPORT==== 26-Apr-2016::06:33:13 ===
accepting AMQP connection <0.2457.0> (192.168.99.1:51159 -> 172.22.0.2:5672)

=INFO REPORT==== 26-Apr-2016::06:33:13 ===
closing AMQP connection <0.2457.0> (192.168.99.1:51159 -> 172.22.0.2:5672)

=INFO REPORT==== 26-Apr-2016::06:33:28 ===
closing AMQP connection <0.2404.0> (192.168.99.1:51158 -> 172.22.0.2:5672)
"""

Thanks again.

**Comment by vitaly-krugl** [comment] 2016-04-26 16:51
@mishas, thanks for the update. Definitely, sharing a connection from multiple threads will lead to problems such as the one that you describe here. I am going to assume that the multi-threaded access is the cause and close this issue. If the problem still persists after fixing multithreading on your end, please open a new issue.

**Closed by vitaly-krugl** 2016-04-26 16:51 UTC
