### ISSUE TITLE
basic_consume hangs indefinitely if connection dies while prefetch_count reached 

### ISSUE THREAD

**Issue by JonathanBrannock** [pika/pika#766] opened 2016-08-26 16:16 UTC
Title says most of it. 

```
channel.basic_qos(prefetch_count=1)
channel.basic_consume(handle_delivery, sourcequeue)
channel.start_consuming()
```

A child process started from handle_delivery raises exceptions.ConnectionClosed()
and prints "The AMQP connection was closed: ()"

The IOLoop continues to run indefinitely with a dead channel.

Maybe I am wrong but shouldn't the IOLoop detect when a channel dies even if the prefetch qos is reached?

**Comment by michaelklishin** [comment] 2016-08-26 16:17
Note that the prefetch value is very likely a total red herring. It all comes down to how a server-initiated connection closure is handled.

**Comment by JonathanBrannock** [comment] 2016-08-26 16:21
From the RabbitMQ Management web page, all of the connections are still there, but they have no channels associated with them.

**Comment by vitaly-krugl** [comment] 2016-08-26 16:47
@JonathanBrannock, it would help if you provided a minimal code sample that reproduces the issue.

In the absence of such example, one thing jumps out in particular:
> A child process started from handle_delivery raises exceptions.ConnectionClosed()

This sounds like your app forks a child process from the `handle_delivery` callback that continues to use the connection/channel that was created in the parent process. This would imply that both child and parent processes are reading/writing the same socket without any coordination.

This leads to corruption of the traffic on the shared TCP/IP stream, and is an unsupported configuration.

**Comment by vitaly-krugl** [comment] 2016-08-26 17:03
Also, depending on the forking parameters, the file descriptors (including sockets) that were created in the parent might be closed in the fork, which would explain "The AMQP connection was closed: ()" in the child process.

In any case, it sounds like your app is using pika in an unsupported way.

**Comment by JonathanBrannock** [comment] 2016-08-26 17:04
You are correct, I am trying to figure out a better way to do this. I am only using the channel to send the ACK/NACK for the message. For everything else the child opens its own channel. I am hesitant to ACK the message before the worker is complete. 

This may be the cause, but this only happens every few days to several times a day at the most. So  its not consistently reproducible.

I started down this rabbit hole because I occasionally have processes that take longer than the rabbitmq 60 second heartbeat to finish.

**Comment by vitaly-krugl** [comment] 2016-08-26 17:13
An instance of a pika connection and anything derived from it (such as a channel) must all be used within the same thread. See "Is Pika thread safe?" in http://pika.readthedocs.io/en/latest/faq.html.

@JonathanBrannock, since this is user error rather than a bug in pika, I am going to close this issue. A great forum to post your question and get help from experienced users is https://groups.google.com/forum/#!forum/rabbitmq-users. There is also https://groups.google.com/forum/#!forum/pika-python, but it gets far less traffic.

On occasion, you might get a bit of misleading advice from someone who claims that they are using the same pika connection from multiple threads, sent billions of messages, and never ever had any trouble. Take such advice with a grain of salt 😃

**Closed by vitaly-krugl** 2016-08-26 17:13 UTC
