### ISSUE TITLE
channel.consume with inactivity_timeout should just stop

### ISSUE THREAD

**Issue by mathieulongtin** [pika/pika#792] opened 2017-01-13 19:44 UTC
There seems to be a new undocumented  `consume` function available on on `BlockingConnection` channels. It says to use it like this:
```
for method, properties, body in channel.consume(queue=queue):
  # Do stuff with message
```

Except if you add the argument `inactivity_timeout=N`, it yields None whenever it's inactive for N seconds, thus you have to change your code to this:
```
for message_tuple in channel.consume(queue=queue, inactivity_timeout=0):
  if message_tuple is None:
    # Do stuff when idle
  else:
    method, properties, body = message_tuple
    # Do stuff with message
```

Wouldn't it make more sense if the iterator just quit and not have a different behavior?

If I really want to do something when idle, I can always restart `channel.consume()`.

**Comment by vitaly-krugl** [comment] 2017-01-13 20:09
Closing as duplicate of #760

**Closed by vitaly-krugl** 2017-01-13 20:09 UTC
