### ISSUE TITLE
Tornado ioloop._Timeout grows with every request

### ISSUE THREAD

**Issue by jaygorrell** [pika/pika#730] opened 2016-04-12 14:28 UTC
This is a strange one that I've been digging into for days. At first, I thought it was completely unrelated to Pika but I've narrowed things down quite a bit to the point where commenting-out my TornadoConnection() prevents the problem from happening.

My setup is completely based on the [Tornado Consumer](http://pika.readthedocs.org/en/latest/examples/tornado_consumer.html) example.

My setup is that I'm running a Tornado API and call the consumer run() method from an ioloop_instance.add_timeout() call with time.time()+1, which happens as soon as I start the ioloop immediately after.

If I do the above, each call to my API adds 2 additions to `tornado.ioloop._Timeout`. If I skip initializing my Pika consumer (or simply comment-out the TornadoConnection in it), everything is fine.

The concern here is that I'm experiencing a pretty hefty memory leak, based on traffic.

Tornado: 4.0.2
Pika: 0.9.14 (Edit: Just tried 0.10.0 with same result)

Any ideas?

**Comment by jaygorrell** [comment] 2016-04-12 16:41
I have thrown together a somewhat minimal test-case to show the problem. I know this has some extras but I tried to keep it relatively clean for investigation.

https://github.com/jaygorrell/pika-tornado-leak

**Comment by gmr** [comment] 2016-04-12 21:45
I'll have to check out what you have going on. I run Tornado + pika in production with very heavy use without memory leaks, so it'll be interesting to troubleshoot.

**Comment by jaygorrell** [comment] 2016-04-12 22:40
If you can cross-reference this implementation with one you know works and point out any flaws, I'd owe you a big one. I've been banging my head on this for some time now. The part killing me is that I don't actually have to use Pika/RMQ at all -- it's the HTTP requests over Tornado that seem to be leaking, but only once I've used a Pika Tornado connection.

Let me know if the test-case project above causes any trouble. If you don't want to use Docker, you'd just need to adjust the hostname and set up the pythonpath for /lib. Everything else should be good.

**Comment by ZMI-BalajiThiruvengadam** [comment] 2016-04-25 14:27
any luck Gavin ?

**Comment by mleva-bnet** [comment] 2016-04-28 16:50
i think were still looking into this a little deeper, but what i see is the following:

when the pika consumer connects to the rabbit server, if no heartbeat interval is explicitly set on the consumer, it will get it from the rabbit server. in rabbit v3.5.5+, this interval is 60 seconds; in versions prior, it is 580 seconds. so the the pika consumer (at app start time) adds a timeout on the tornado ioloop for 580 seconds from now.

as requests come in, tornado adds timeouts of 3600 seconds (1 hour) to the ioloop for idle connection timeouts. however, as the http requests are served, tornado removes these timeouts. removing a timeout actually just sets its callback to None, so the timeout still exists in tornados timeout list.

for every event on the ioloop, tornado checks the first item in the timeout list. if it has expired or its callback is set to None, it will pop it off the list and proceed to the next timeout in the list. otherwise, it stops there and will check again on the next ioloop event. so what we see happening is requests 'leak' for 580 seconds. then, once the heartbeat timeout expires, tornado removes all the idle request timeouts. at least, thats what i saw in my small tests. maybe there is something else going on when this happens at scale, but we are still looking here and elsewhere in our code.

let us know if you find anything @gmr

**Comment by vitaly-krugl** [comment] 2016-04-28 19:39
@jaygorrell: Calling the [Tornado consumer example's run](https://github.com/pika/pika/blame/12b793f3c06c933a581a5b67cf0bebce355b689b/docs/examples/tornado_consumer.rst#L312-L318) method as-is only makes sense if you haven't started the ioloop yet. In your issue description, you said that you start the ioloop yourself ("which happens as soon as I start the ioloop immediately after"), so you need to modify the example's `run` method.  

The `run` method in the Tornado Consumer example does these two things:
```
            self._connection = self.connect()
            self._connection.ioloop.start()
```

If you already started the ioloop, and if it's the same loop that your TornadoConnection should be running on, then you probably don't want the additional `self._connection.ioloop.start()`. 

Also, if your app uses a non-default ioloop (i.e., not `ioloop.IOLoop.instance()`), then you need to pass the ioloop that you're using to the TornadoConnection constructor, if you want TornadoConnection to run on the same ioloop. If you don't pass an ioloop to TornadoConnection, then it defaults to `ioloop.IOLoop.instance()`.

Finally, make sure you're not calling the example's `run` method from a repeating timer. Instrument the consumer methods with log or print statements and see what is actually happening there.

**Comment by vitaly-krugl** [comment] 2016-04-28 19:41
Enable DEBUG-level logging before creating TornadoConnection, and review the pika (as well as your own) log output to make sure that nothing strange is going on. Something like this should work: 

```
import logging

logging.basicConfig(level=logging.DEBUG)
```

**Comment by jaygorrell** [comment] 2016-04-29 00:35
@vitaly-krugl Please see the linked example project above: https://github.com/jaygorrell/pika-tornado-leak You can see the run method is already modified to not start the ioloop as you suggested. It simply connects with the Tornado adapter. And yes, this is a default ioloop instance and run is only called once. All of this is in the example project to show a repeatable test-case.

@mleva-bnet Have you verified that the timeouts get removed after one hour? I thought for sure some of my tests went much longer but I may be mistaken.

**Comment by mleva-bnet** [comment] 2016-04-29 17:28
@jaygorrell as soon as the http requests are served, tornado removes their timeout, which just sets their callback to None (they are still in the timeout list, but callback=None). so once the pika heartbeat timeout fires (every ~580 seconds), tornado handles the pika heartbeat timeout, then proceeds down the ioloop timeout list removing/handling all timeouts that have either expired or have callback set to None. in my small scale tests, the request timeouts were removed as soon as the pika heartbeat timeout fired. you can test this by setting the heartbeat timeout on the consumer in your `TornadoPikaPublisher` init:

```
        self.amqp_url = amqp_url + '?heartbeat_interval=30'
```

youll see the timeouts list empty out every 30 seconds

**Comment by jaygorrell** [comment] 2016-04-29 18:37
In the real use-case, these callbacks were definitely set to an object and not None, so they weren't cleaned up. If that's not the case in the example project above then I've accidentally taken something out that's needed to show this. :(

**Comment by mleva-bnet** [comment] 2016-04-29 19:28
the ioloop's `_timeouts` list contains `_Timeout` objects. `_Timeout` objects have `deadline`, `callback`, and `tiebreaker` attributes. the `_timeouts` list will definitely contain non-None objects, but those objects (in the case of the http request 1hr timeout) will have their `callback` attribute set to `None` once the request is served. are you sure youre not thinking about the `_Timeout` object?

**Comment by jaygorrell** [comment] 2016-04-29 19:30
You may be correct, it's been a bit since looking.

In that case, when you see the _timeouts get reset to None, does the memory in use get cleared up as well? I was definitely seeing a steady leak of memory over time, based on HTTP requests.

**Comment by mleva-bnet** [comment] 2016-04-29 19:38
in theory, they shouldve been cleaned up anyway since the callback was set to None, thus releasing the reference. True, the `_Timeout` objects would temporarily leak, but not the `HTTP1Connection` objects. i didnt look into the memory side of things much; just tried to understand why the timeouts list was growing. jg is delving deeper now.

**Comment by mleva-bnet** [comment] 2016-05-04 00:07
jacob found the leak. it was in the old version (7.40) of libcurl available in the amazon linux ami

https://github.com/curl/curl/issues/147

https://aws.amazon.com/amazon-linux-ami/2015.09-packages/

unless there are still suspicions, you can close this issue.

**Comment by vitaly-krugl** [comment] 2016-05-04 04:54
Thanks for the update. Closing as sue to libcurl, not caused by pika.

**Closed by vitaly-krugl** 2016-05-04 04:54 UTC

**Comment by jaygorrell** [comment] 2016-05-04 12:04
Awesome, nice catch. Still not updated in the latest AMI, either: https://aws.amazon.com/amazon-linux-ami/2016.03-packages/
