### ISSUE TITLE
Infinite loop with BlockingConnection if connection address is not actual rabbitmq

### ISSUE THREAD

**Issue by quozd** [pika/pika#985] opened 2018-03-02 14:03 UTC
Hello, i'm trying to do a post-deploy health check of my app to verify everything is running and properly configured and get infinite loop with BlockingConnection if connection host is not rabbitmq.

Case:
Host and port for rabbitmq is misconfigured and there is Redis instance on specified address, not RabbitMq. 

Python:
```
$ python -V
Python 3.5.2
```

Pika:
```
$ pip show pika
---
Metadata-Version: 2.0
Name: pika
Version: 0.11.2
```

Code:
```python
connection = pika.BlockingConnection(
    parameters=pika.ConnectionParameters(
        host=config.host,
        port=config.port,
        virtual_host=config.vhost,
        credentials=pika.PlainCredentials(
            username=config.user,
            password=config.password,
        )
    )
) # never returns
channel = connection.channel()
#....
```

Steps to reproduce:
Set `config.host` and `config.port` to any other running service (e.g. Redis instance)

Expected result:
Any kind of exception to be thrown on timeout

Actual result:
Infinite loop in [blocking_connection/BlockingConnection/_flush_output](https://github.com/pika/pika/blob/master/pika/adapters/blocking_connection.py#L459-L461)

Would be very nice to add some kind of timeout to prevent such situations.

**Comment by lukebakken** [comment] 2018-03-02 23:19
Thanks for the report. I can reproduce with the attached file.
[repro.py.txt](https://github.com/pika/pika/files/1776811/repro.py.txt)

@vitaly-krugl thoughts? Some operations (like `consume`) have an inactivity timeout.

I don't think this is a high-priority issue to fix at the moment.

**Comment by vitaly-krugl** [comment] 2018-03-03 01:03
A debug pika log from beginning leading to the hang would be very nice.

I am surprised that `pika.BlockingConnection()` constructor returns at all without encountering an error and raising an exception. How does the AMQP handshake even complete if the server is not AMQP?

**Comment by vitaly-krugl** [comment] 2018-03-03 06:05
@lukebakken - This is not terribly urgent, but I would like to get the requested info to understand it better.

**Comment by vitaly-krugl** [comment] 2018-03-03 06:43
1. To reiterate, it's strange that AMQP handshake would succeed when connected to Redis. @lukebakken  - any idea? Are you sure that the BlockingConnection constructor ever returns?
2. If it's actually stuck in the constructor (i.e., never gets to the `connection.channel()` call), then (like #647), the situation would be helped by having a built-in AMQP handshake timeout.
3. If it magically completes the AMQP handshake, then the situation would be helped by fixing the heartbeat timeout logic as I described in https://github.com/pika/pika/issues/708#issuecomment-370105566.

**Comment by lukebakken** [comment] 2018-03-03 16:01
@vitaly-krugl the debug log shows the TCP connection is established, and the `AMQP0091` message is sent (I can see that in Wireshark). There is no response and the handshake never completes. Redis never shuts down the TCP socket, and Pika doesn't have a timeout for the handshake completion.

I'll attach the debug log and Wireshark trace when I can.

**Comment by vitaly-krugl** [comment] 2018-03-03 19:00
@lukebakken, thank you for confirming that it gets stuck in the handshake. So, the `channel = connection.channel()` call is unnecessary for reproducing this issue.

So, having a handshake timeout in `Connection` that calls `Connection._on_terminate(...)` should resolve both #647 and this issue.

**Comment by michaelklishin** [comment] 2018-03-04 15:37
My 2¢: handshake timeouts are present in all official and most popular clients.

**Comment by vitaly-krugl** [comment] 2018-03-04 19:10
@michaelklishin, do you recommend making the handshake timeout configurable by user? And what do your recommend as the (default) value?

**Comment by michaelklishin** [comment] 2018-03-06 23:31
@vitaly-krugl yes, since any default library maintainers pick is going to be wrong ;) [Java](https://github.com/rabbitmq/rabbitmq-java-client/blob/a56f85b5f59ee36b09bf7d9c2d60153fffe993b7/src/main/java/com/rabbitmq/client/ConnectionFactory.java#L92) and [.NET](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/3c3827cd45e02b2abfa1eaffb6c987edf08118a1/projects/client/RabbitMQ.Client/src/client/api/ConnectionFactory.cs#L174) clients use the same value of 10 seconds.

**Comment by michaelklishin** [comment] 2018-03-06 23:32
Bunny doesn't have a handshake timeout per se but it does have a TCP connection timeout, socket operation timeouts and channel continuation timeouts, so collectively that's sufficient but produces slightly different error messages.

**Comment by vitaly-krugl** [comment] 2018-03-06 23:48
Thank you!

**Comment by vitaly-krugl** [comment] 2018-04-06 07:15
I am refactoring the transport in PR #1002, which includes an overall TCP/[SSL]/AMQP connection timeout, so should also address this hang.

**Comment by vitaly-krugl** [comment] 2018-04-06 14:49
@lukebakken, this is one of the issues that is being addressed by my refactoring PR #1002. Should I re-assign this issue to myself?

**Comment by lukebakken** [comment] 2018-04-10 15:35
@vitaly-krugl done! Thanks.

**Closed** 2018-04-26 14:59 UTC

**Comment by quozd** [comment] 2018-04-26 16:25
👍👍 when this expected to be released?

**Comment by lukebakken** [comment] 2018-04-26 16:40
@quozd when it is done. There is no ETA at this time. You could start testing the `master` branch and we would be very appreciative. Please note that there will be incompatible API changes in version `1.0.0`.
