### ISSUE TITLE
multiprocess pika connection

### ISSUE THREAD

**Issue by Johnathon332** [pika/pika#715] opened 2016-03-07 15:50 UTC
I am trying to set up a consumer in another process however it seems to hang when I try to run it in another process rather than the main process.  I have copied the async example consumer,  here is part of my code where I fire it off I have added a constructor to the class to initiate some custom member variables, however nothing in the main body of the class has changed as of yet.

```
def register():
        registration = ExampleConsumer('amqp://guest:guest@localhost:5672/%2F', 'messaging', 'direct',
                                       'outboundMessaging',
                                       'outbound', ws, 'RegisteredCallback')
        try:
            reg = Process(target=registration.run)
            reg.start()
        except KeyboardInterrupt:
            registration.stop()
```

and it stalls on this:
`INFO       2016-03-07 15:29:03,166 __main__                       connect                              447 : Connecting to amqp://guest:guest@localhost:5672/%2F
`

**Comment by vitaly-krugl** [comment] 2016-03-07 19:43
@Johnathon332, you will want to try a few things:

1. Before you start running it in another process, are you able to get it to work in the main process?
2. I shy away from instantiating communications objects in one process and using them in another. This is because sockets and other kernel objects that they create in the main process (anything that has file descriptors) tend to get duped into the forked process. This might create problems related to the lifetime of those duped file descriptors. For example, when the the other process closes a duped socket, the connection might not get closed, because the main process might not have closed its instance of that same connection. It's better to pass the arguments to the other process and let the other process instantiate ExampleConsumer, etc.
3. pika has pretty useful debug-level logging for debugging connectivity and other problems. Turn on debug-level logging before you create ExampleConsumer. E.g., `import logging; logging.basicConfig(level=logging.DEBUG)`; then, use the logging information to debug the problem.

Also, post information about your environment that would be helpful for debugging, such as versions of pika and python, the operating system, DEBUG-level logs, etc.

**Comment by Johnathon332** [comment] 2016-03-08 08:45
1) I am able to get it running on the main process.
2) I have taken your advice and instantiated the connection object within the process.
3) I have turned on debugging however it hangs on this `INFO       2016-03-08 08:43:07,991 __main__                       connect                              447 : Connecting to amqp://guest:guest@localhost:5672/%2F
`

**Comment by vitaly-krugl** [comment] 2016-03-08 16:51
Is there any other log output from pika besides the one line that you posted?

**Comment by vitaly-krugl** [comment] 2016-03-08 16:54
Also, it might help to attach (as a file or link to a gist) a complete, simple, functional script that demonstrates the issue. In your attachment, rid everything from ExampleConsumer that isn't necessary to reproduce this issue.

**Comment by gmr** [comment] 2016-04-01 00:18
Why would you start the connection before forking a child process? Just open a connection per child process.

**Comment by vitaly-krugl** [comment] 2016-04-24 17:37
Closing due to inactivity

**Closed by vitaly-krugl** 2016-04-24 17:37 UTC
