### ISSUE TITLE
BlockingConnection simple_publish eating memory.

### ISSUE THREAD

**Issue by corpulent** [pika/pika#749] opened 2016-05-16 19:35 UTC
I am using pika to publish messages from a Django app,  everytime I publish a message,  my memory usage increases a bit,  overtime the server crashes because it runs out of memory.  I can't figure out what is causing this memory leak.  I am using the publishing example from here https://github.com/pika/pika/blob/master/examples/publish.py.  I call this script from my Django app via `subprocess.Popen`,  I also tried wrapping into a Pyro4 object.  Nothing helps,  I always get the memory leak.  Any thoughts?

**Comment by vitaly-krugl** [comment] 2016-05-16 21:47
Which OS and version of pika are you using?

If you're wrapping your entire pika session in a Popen, and then reaping the subprocess (confirming that it completed), I don't see how pika could be contributing to memory leaks, since the operating system is responsible for cleaning up memory upon process termination. Are you sure that the subprocesses are terminating in a timely manner?

It would help to isolate the code into a simpler app; for example, eliminate Django, and just implement a simple python app that publishes messages using subprocess.Popen, and checking to make sure that the process completes, etc.

Post the simple code example that actually reproduces the problem without Django.

**Comment by eandersson** [comment] 2016-06-04 23:25
Is this with the latest RabbitMQ version (3.6.2?)

**Comment by corpulent** [comment] 2016-06-09 11:09
I resolved this by stopping the logging.

**Comment by vitaly-krugl** [comment] 2016-06-14 01:49
Thanks for the update, closing...

**Closed by vitaly-krugl** 2016-06-14 01:49 UTC
