### ISSUE TITLE
BlockingChannel Publish never completes

### ISSUE THREAD

**Issue by markunsworth** [pika/pika#708] opened 2016-02-17 15:54 UTC
We have got a bit of a strange situation where publishing to RabbitMQ sometimes, randomly, hangs on a publish call. However the message seems to have been published successfully as I can see that downstream services have successfully consumed and processed the message.

The service runs an async consumer (SelectConnection) to a queue, it does it's work and then uses a BlockingConnection to publish to a fanout exchange. The publisher's Connection is opened once at service startup and then we just call publish each time we want to send a message as we're processing 100s of messages per second so connecting for every message would be a huge overhead. However if we do catch a ChannelClosed, AMQPConnectionError or ConnectionClosed we recreate the connection and channel again.

After calling publish the connection eventually times out after ~15mins, which doesn't match the 580s heartbeat we set on the connection so not sure what chooses that particular time frame.

Heres the debug logs from the service:

```
2016-02-17 11:16:26,995 pika.adapters.base_connection ERROR  Socket Error: 110
2016-02-17 11:16:26,996 pika.connection      WARNING Disconnected from RabbitMQ *REMOVED_HOST_AND_PORT* (-1): error(110, 'Connection timed out')
2016-02-17 11:16:26,996 pika.heartbeat       DEBUG  Removing timeout for next heartbeat interval
2016-02-17 11:16:26,996 pika.adapters.select_connection DEBUG  remove_timeout: removed 8772215559929332180
2016-02-17 11:16:26,996 pika.channel         INFO   <METHOD(['channel_number=1', 'frame_type=1', 'method=<Channel.Close([\'reply_code=-1\', "reply_text=error(110, \'Connection timed out\')"])>'])>
2016-02-17 11:16:26,996 pika.channel         WARNING Received remote Channel.Close (-1): error(110, 'Connection timed out')
2016-02-17 11:16:26,996 pika.callback        DEBUG  Processing 1:_on_channel_cleanup
2016-02-17 11:16:26,996 pika.callback        DEBUG  Processing use of oneshot callback
2016-02-17 11:16:26,996 pika.callback        DEBUG  0 registered uses left
2016-02-17 11:16:26,996 pika.callback        DEBUG  Removing callback #0: {'callback': <bound method SelectConnection._on_channel_cleanup of <pika.adapters.select_connection.SelectConnection object at 0x7f49a1ef0110>>, 'only': <pika.channel.Channel object at 0x7f49a1ef07d0>, 'one_shot': True, 'arguments': None, 'calls': 0}
2016-02-17 11:16:26,996 pika.callback        DEBUG  Calling <bound method SelectConnection._on_channel_cleanup of <pika.adapters.select_connection.SelectConnection object at 0x7f49a1ef0110>> for "1:_on_channel_cleanup"
2016-02-17 11:16:26,996 pika.connection      DEBUG  Removed channel 1
2016-02-17 11:16:26,996 pika.callback        DEBUG  Clearing out '1' from the stack
2016-02-17 11:16:26,997 pika.callback        DEBUG  Processing 0:_on_connection_closed
2016-02-17 11:16:26,997 pika.callback        DEBUG  Calling <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x7f49a1e2ae60>> for "0:_on_connection_closed"
2016-02-17 11:16:26,997 pika.callback        DEBUG  Added: {'callback': <bound method SelectConnection._on_connection_start of <pika.adapters.select_connection.SelectConnection object at 0x7f49a1ef0110>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 1}
2016-02-17 11:16:26,997 pika.callback        DEBUG  Incremented callback reference counter: {'callback': <bound method SelectConnection._on_connection_close of <pika.adapters.select_connection.SelectConnection object at 0x7f49a1ef0110>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 2}
2016-02-17 11:16:26,997 pika.adapters.blocking_connection ERROR  Connection close detected; result=BlockingConnection__OnClosedArgs(connection=<pika.adapters.select_connection.SelectConnection object at 0x7f49a1ef0110>, reason_code=-1, reason_text="error(110, 'Connection timed out')")
2016-02-17 11:16:26,997 knowsis.data.rabbitmq.job_sender INFO   Connection closed while sending message *REMOVED_MESSAGE_BODY*, reopening
2016-02-17 11:16:26,997 knowsis.data.rabbitmq.job_sender INFO   Creating a connection
2016-02-17 11:16:26,997 pika.adapters.select_connection DEBUG  Using EPollPoller
2016-02-17 11:16:26,997 pika.callback        DEBUG  Added: {'callback': <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x7f49a1e2ad88>>, 'only': None, 'one_shot': False, 'arguments': None}
2016-02-17 11:16:26,997 pika.callback        DEBUG  Added: {'callback': <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x7f49a1e2a998>>, 'only': None, 'one_shot': False, 'arguments': None}
2016-02-17 11:16:26,997 pika.callback        DEBUG  Added: {'callback': <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x7f49a1e2a878>>, 'only': None, 'one_shot': False, 'arguments': None}
2016-02-17 11:16:26,997 pika.callback        DEBUG  Added: {'callback': <bound method SelectConnection._on_connection_start of <pika.adapters.select_connection.SelectConnection object at 0x7f49a1ef0ed0>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 1}
2016-02-17 11:16:26,998 pika.callback        DEBUG  Added: {'callback': <bound method SelectConnection._on_connection_close of <pika.adapters.select_connection.SelectConnection object at 0x7f49a1ef0ed0>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 1}
2016-02-17 11:16:27,014 pika.adapters.base_connection INFO   Connecting to *REMOVED_HOST_AND_PORT*
2016-02-17 11:16:27,021 pika.callback        DEBUG  Processing 0:Connection.Start
2016-02-17 11:16:27,021 pika.callback        DEBUG  Processing use of oneshot callback
2016-02-17 11:16:27,022 pika.callback        DEBUG  0 registered uses left
2016-02-17 11:16:27,022 pika.callback        DEBUG  Removing callback #0: {'callback': <bound method SelectConnection._on_connection_start of <pika.adapters.select_connection.SelectConnection object at 0x7f49a1ef0ed0>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 0}
2016-02-17 11:16:27,022 pika.callback        DEBUG  Calling <bound method SelectConnection._on_connection_start of <pika.adapters.select_connection.SelectConnection object at 0x7f49a1ef0ed0>> for "0:Connection.Start"
2016-02-17 11:16:27,022 pika.callback        DEBUG  Added: {'callback': <bound method SelectConnection._on_connection_tune of <pika.adapters.select_connection.SelectConnection object at 0x7f49a1ef0ed0>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 1}
2016-02-17 11:16:27,025 pika.callback        DEBUG  Processing 0:Connection.Tune
2016-02-17 11:16:27,025 pika.callback        DEBUG  Processing use of oneshot callback
2016-02-17 11:16:27,025 pika.callback        DEBUG  0 registered uses left
2016-02-17 11:16:27,025 pika.callback        DEBUG  Removing callback #0: {'callback': <bound method SelectConnection._on_connection_tune of <pika.adapters.select_connection.SelectConnection object at 0x7f49a1ef0ed0>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 0}
2016-02-17 11:16:27,025 pika.callback        DEBUG  Calling <bound method SelectConnection._on_connection_tune of <pika.adapters.select_connection.SelectConnection object at 0x7f49a1ef0ed0>> for "0:Connection.Tune"
2016-02-17 11:16:27,025 pika.connection      DEBUG  Creating a HeartbeatChecker: 580
2016-02-17 11:16:27,025 pika.adapters.select_connection DEBUG  add_timeout: added timeout -7607233669822406284; deadline=580 at 1455708367.03
2016-02-17 11:16:27,026 pika.callback        DEBUG  Added: {'callback': <bound method SelectConnection._on_connection_open of <pika.adapters.select_connection.SelectConnection object at 0x7f49a1ef0ed0>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 1}
2016-02-17 11:16:27,029 pika.callback        DEBUG  Processing 0:Connection.OpenOk
2016-02-17 11:16:27,029 pika.callback        DEBUG  Processing use of oneshot callback
2016-02-17 11:16:27,029 pika.callback        DEBUG  0 registered uses left
2016-02-17 11:16:27,029 pika.callback        DEBUG  Removing callback #0: {'callback': <bound method SelectConnection._on_connection_open of <pika.adapters.select_connection.SelectConnection object at 0x7f49a1ef0ed0>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 0}
2016-02-17 11:16:27,029 pika.callback        DEBUG  Calling <bound method SelectConnection._on_connection_open of <pika.adapters.select_connection.SelectConnection object at 0x7f49a1ef0ed0>> for "0:Connection.OpenOk"
2016-02-17 11:16:27,029 pika.callback        DEBUG  Processing 0:_on_connection_open
2016-02-17 11:16:27,029 pika.callback        DEBUG  Calling <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x7f49a1e2a998>> for "0:_on_connection_open"
2016-02-17 11:16:27,029 knowsis.data.rabbitmq.job_sender INFO   Creating a channel
2016-02-17 11:16:27,029 pika.connection      DEBUG  Creating channel 1
2016-02-17 11:16:27,029 pika.callback        DEBUG  Added: {'callback': <bound method SelectConnection._on_channel_cleanup of <pika.adapters.select_connection.SelectConnection object at 0x7f49a1ef0ed0>>, 'only': <pika.channel.Channel object at 0x7f49a1ef0e50>, 'one_shot': True, 'arguments': None, 'calls': 1}
2016-02-17 11:16:27,029 pika.callback        DEBUG  Added: {'callback': <bound method Channel._on_getempty of <pika.channel.Channel object at 0x7f49a1ef0e50>>, 'only': None, 'one_shot': False, 'arguments': None}
2016-02-17 11:16:27,029 pika.callback        DEBUG  Added: {'callback': <bound method Channel._on_cancel of <pika.channel.Channel object at 0x7f49a1ef0e50>>, 'only': None, 'one_shot': False, 'arguments': None}
2016-02-17 11:16:27,030 pika.callback        DEBUG  Added: {'callback': <bound method Channel._on_flow of <pika.channel.Channel object at 0x7f49a1ef0e50>>, 'only': None, 'one_shot': False, 'arguments': None}
2016-02-17 11:16:27,030 pika.callback        DEBUG  Added: {'callback': <bound method Channel._on_close of <pika.channel.Channel object at 0x7f49a1ef0e50>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 1}
2016-02-17 11:16:27,030 pika.channel         DEBUG  Entering blocking state on frame <Channel.Open(['out_of_band='])>; acceptable_replies=[<class 'pika.spec.OpenOk'>]
2016-02-17 11:16:27,030 pika.channel         DEBUG  Adding on_synchronous_complete callback
2016-02-17 11:16:27,030 pika.callback        DEBUG  Added: {'callback': <bound method Channel._on_synchronous_complete of <pika.channel.Channel object at 0x7f49a1ef0e50>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 1}
2016-02-17 11:16:27,030 pika.channel         DEBUG  Adding passed-in callback
2016-02-17 11:16:27,030 pika.callback        DEBUG  Added: {'callback': <bound method Channel._on_openok of <pika.channel.Channel object at 0x7f49a1ef0e50>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 1}
2016-02-17 11:16:27,030 pika.callback        DEBUG  Added: {'callback': <bound method BlockingChannel._on_consumer_cancelled_by_broker of <pika.adapters.blocking_connection.BlockingChannel object at 0x7f49a1ef0390>>, 'only': None, 'one_shot': False, 'arguments': None}
2016-02-17 11:16:27,030 pika.callback        DEBUG  Added: {'callback': <bound method _CallbackResult.signal_once of <pika.adapters.blocking_connection._CallbackResult object at 0x7f49a1e293f8>>, 'only': None, 'one_shot': False, 'arguments': None}
2016-02-17 11:16:27,030 pika.callback        DEBUG  Added: {'callback': <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x7f49a1e29830>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 1}
2016-02-17 11:16:27,030 pika.callback        DEBUG  Added: {'callback': <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x7f49a1e29cf8>>, 'only': None, 'one_shot': False, 'arguments': None}
2016-02-17 11:16:27,030 pika.adapters.blocking_connection INFO   Created channel=1
2016-02-17 11:16:27,033 pika.callback        DEBUG  Processing 1:Channel.OpenOk
2016-02-17 11:16:27,034 pika.callback        DEBUG  Processing use of oneshot callback
2016-02-17 11:16:27,034 pika.callback        DEBUG  0 registered uses left
2016-02-17 11:16:27,034 pika.callback        DEBUG  Removing callback #0: {'callback': <bound method Channel._on_synchronous_complete of <pika.channel.Channel object at 0x7f49a1ef0e50>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 0}
2016-02-17 11:16:27,034 pika.callback        DEBUG  Processing use of oneshot callback
2016-02-17 11:16:27,034 pika.callback        DEBUG  0 registered uses left
2016-02-17 11:16:27,035 pika.callback        DEBUG  Removing callback #0: {'callback': <bound method Channel._on_openok of <pika.channel.Channel object at 0x7f49a1ef0e50>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 0}
2016-02-17 11:16:27,035 pika.callback        DEBUG  Calling <bound method Channel._on_synchronous_complete of <pika.channel.Channel object at 0x7f49a1ef0e50>> for "1:Channel.OpenOk"
2016-02-17 11:16:27,035 pika.channel         DEBUG  0 blocked frames
2016-02-17 11:16:27,035 pika.callback        DEBUG  Calling <bound method Channel._on_openok of <pika.channel.Channel object at 0x7f49a1ef0e50>> for "1:Channel.OpenOk"
2016-02-17 11:16:27,036 knowsis.data.rabbitmq.job_sender INFO   Setting channel to confirm deliveries
2016-02-17 11:16:27,036 pika.callback        DEBUG  Added: {'callback': <bound method _CallbackResult.signal_once of <pika.adapters.blocking_connection._CallbackResult object at 0x7f49a1e290e0>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 1}
2016-02-17 11:16:27,036 pika.callback        DEBUG  Added: {'callback': <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x7f49a1e2ab48>>, 'only': None, 'one_shot': False, 'arguments': None}
2016-02-17 11:16:27,036 pika.callback        DEBUG  Added: {'callback': <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x7f49a1e2ab48>>, 'only': None, 'one_shot': False, 'arguments': None}
2016-02-17 11:16:27,036 pika.channel         DEBUG  Entering blocking state on frame <Confirm.Select(['nowait=False'])>; acceptable_replies=[<class 'pika.spec.SelectOk'>]
2016-02-17 11:16:27,037 pika.channel         DEBUG  Adding on_synchronous_complete callback
2016-02-17 11:16:27,037 pika.callback        DEBUG  Added: {'callback': <bound method Channel._on_synchronous_complete of <pika.channel.Channel object at 0x7f49a1ef0e50>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 1}
2016-02-17 11:16:27,037 pika.channel         DEBUG  Adding passed-in callback
2016-02-17 11:16:27,037 pika.callback        DEBUG  Added: {'callback': <bound method Channel._on_selectok of <pika.channel.Channel object at 0x7f49a1ef0e50>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 1}
2016-02-17 11:16:27,040 pika.callback        DEBUG  Processing 1:Confirm.SelectOk
2016-02-17 11:16:27,040 pika.callback        DEBUG  Processing use of oneshot callback
2016-02-17 11:16:27,040 pika.callback        DEBUG  0 registered uses left
2016-02-17 11:16:27,041 pika.callback        DEBUG  Removing callback #0: {'callback': <bound method _CallbackResult.signal_once of <pika.adapters.blocking_connection._CallbackResult object at 0x7f49a1e290e0>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 0}
2016-02-17 11:16:27,041 pika.callback        DEBUG  Processing use of oneshot callback
2016-02-17 11:16:27,041 pika.callback        DEBUG  0 registered uses left
2016-02-17 11:16:27,041 pika.callback        DEBUG  Removing callback #0: {'callback': <bound method Channel._on_synchronous_complete of <pika.channel.Channel object at 0x7f49a1ef0e50>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 0}
2016-02-17 11:16:27,042 pika.callback        DEBUG  Processing use of oneshot callback
2016-02-17 11:16:27,042 pika.callback        DEBUG  0 registered uses left
2016-02-17 11:16:27,042 pika.callback        DEBUG  Removing callback #0: {'callback': <bound method Channel._on_selectok of <pika.channel.Channel object at 0x7f49a1ef0e50>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 0}
2016-02-17 11:16:27,042 pika.callback        DEBUG  Calling <bound method _CallbackResult.signal_once of <pika.adapters.blocking_connection._CallbackResult object at 0x7f49a1e290e0>> for "1:Confirm.SelectOk"
2016-02-17 11:16:27,042 pika.callback        DEBUG  Calling <bound method Channel._on_synchronous_complete of <pika.channel.Channel object at 0x7f49a1ef0e50>> for "1:Confirm.SelectOk"
2016-02-17 11:16:27,043 pika.channel         DEBUG  0 blocked frames
2016-02-17 11:16:27,043 pika.callback        DEBUG  Calling <bound method Channel._on_selectok of <pika.channel.Channel object at 0x7f49a1ef0e50>> for "1:Confirm.SelectOk"
2016-02-17 11:16:27,043 pika.channel         DEBUG  Confirm.SelectOk Received: <METHOD(['channel_number=1', 'frame_type=1', 'method=<Confirm.SelectOk>'])>
2016-02-17 11:16:27,043 pika.callback        DEBUG  Added: {'callback': <bound method BlockingChannel._on_puback_message_returned of <pika.adapters.blocking_connection.BlockingChannel object at 0x7f49a1ef0390>>, 'only': None, 'one_shot': False, 'arguments': None}
2016-02-17 11:16:27,043 knowsis.data.rabbitmq.job_sender INFO   Creating durable fanout exchange: searchresult_parsed
2016-02-17 11:16:27,044 pika.channel         DEBUG  Entering blocking state on frame <Exchange.Declare(['arguments={}', 'auto_delete=False', 'durable=True', 'exchange=searchresult_parsed', 'internal=False', 'nowait=False', 'passive=False', 'ticket=0', 'type=fanout'])>; acceptable_replies=[<class 'pika.spec.DeclareOk'>]
2016-02-17 11:16:27,044 pika.channel         DEBUG  Adding on_synchronous_complete callback
2016-02-17 11:16:27,044 pika.callback        DEBUG  Added: {'callback': <bound method Channel._on_synchronous_complete of <pika.channel.Channel object at 0x7f49a1ef0e50>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 1}
2016-02-17 11:16:27,044 pika.channel         DEBUG  Adding passed-in callback
2016-02-17 11:16:27,044 pika.callback        DEBUG  Added: {'callback': <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x7f49a1e290e0>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 1}
2016-02-17 11:16:27,047 pika.callback        DEBUG  Processing 1:Exchange.DeclareOk
2016-02-17 11:16:27,048 pika.callback        DEBUG  Processing use of oneshot callback
2016-02-17 11:16:27,048 pika.callback        DEBUG  0 registered uses left
2016-02-17 11:16:27,048 pika.callback        DEBUG  Removing callback #0: {'callback': <bound method Channel._on_synchronous_complete of <pika.channel.Channel object at 0x7f49a1ef0e50>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 0}
2016-02-17 11:16:27,048 pika.callback        DEBUG  Processing use of oneshot callback
2016-02-17 11:16:27,048 pika.callback        DEBUG  0 registered uses left
2016-02-17 11:16:27,049 pika.callback        DEBUG  Removing callback #0: {'callback': <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x7f49a1e290e0>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 0}
2016-02-17 11:16:27,049 pika.callback        DEBUG  Calling <bound method Channel._on_synchronous_complete of <pika.channel.Channel object at 0x7f49a1ef0e50>> for "1:Exchange.DeclareOk"
2016-02-17 11:16:27,049 pika.channel         DEBUG  0 blocked frames
2016-02-17 11:16:27,049 pika.callback        DEBUG  Calling <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x7f49a1e290e0>> for "1:Exchange.DeclareOk"
2016-02-17 11:16:27,049 knowsis.data.rabbitmq.job_sender INFO   Exchange searchresult_parsed created
2016-02-17 11:16:27,050 knowsis.data.rabbitmq.job_sender INFO   Connection & channel created and opened
2016-02-17 11:16:27,050 knowsis.data.rabbitmq.job_sender DEBUG  Publishing: *REMOVED_MESSAGE_BODY*
```

The rabbitmq logs don't show anything useful, they just show a number of connection_closed_abruptly warnings:

```
Feb 17 11:13:32 rabbitmq-node0 rabbitmq: =WARNING REPORT==== 17-Feb-2016::11:13:32 ===
Feb 17 11:13:32 rabbitmq-node0 rabbitmq: closing AMQP connection <0.8850.1> (10.0.0.129:21271 -> 10.0.1.196:5672):
Feb 17 11:13:32 rabbitmq-node0 rabbitmq: connection_closed_abruptly
```

I initially thought this was linked to upgrading the server to 3.6.0, but on rolling back to 3.5.7 we are still seeing the same problems. Any thoughts on what's causing this?

**Comment by vitaly-krugl** [comment] 2016-02-17 18:42
Please provide additional information:

1. Platform (windows/linux/etc. and version) where the pika code that produced the above log was executing
2. Network topology; e.g., using ELB, firewall, proxy
3. A short code sample that represents how your app is using pika. Are threads involved, by the way?
4. More logs: it would help to see more of the DEBUG-level pika logs, starting from the moment that BlockingConnection was established. Can you create a gist and link to it from this issue?

**Comment by markunsworth** [comment] 2016-02-22 11:01
I think this is/was down to the network topology. We recently moved from internally managed NAT servers to AWS Managed NAT gateways which would pretty much coincide with this problem starting. The network setup:

service (private subnet) -> nat gateway -> ELB -> rabbitmq cluster (public subnet)

In an attempt to resolve this I decided to try moving the rabbitmq cluster inside the private subnet so the setup is now:

service (private subnet) -> internal ELB -> rabbitmq cluster (private subnet)

This seems to have solved the issue we were seeing, but i'm now trying to investigate with AWS if the NAT Gateway was the root cause of this, and if so why.

In answer to your other questions:

1) Ubuntu 14.04 (64 bit)

3/4) I will create some gists with these too.

**Comment by vitaly-krugl** [comment] 2016-02-22 18:13
From past experience with AWS ELBs, I recall some additional trouble that they might present: they used to have a fixed 60-second timeout on connections, such that if there was no traffic on a connection for that amount of time, the ELB would sever that TCP/IP socket connection.

**Comment by markunsworth** [comment] 2016-02-22 21:52
Yeah, we've been running RabbitMQ behind ELBs for a couple of years and dealt with that by increasing the ELB timeout to be greater than the heartbeat value set on rabbit (600s for ELB & 580s for rabbit)

**Comment by vitaly-krugl** [comment] 2016-02-22 22:19
Ok. By the way, recent versions of RabbitMQ (3.5.5+?) default to a much shorter heartbeat timeout of 60 seconds (instead of 580). So, if newer RabbitMQ with default config doesn't hear from your app on a given connection in 60 seconds, it drops the connection.

**Comment by markunsworth** [comment] 2016-02-23 09:51
Yes, I was aware of that. We deploy rabbit with chef so have configuration overrides on place. I

The strangest thing for me was the fact it was over 15mins (almost always around 15m 30s) before the publish actually timed out as that's a value we can't find in any configuration

**Comment by vitaly-krugl** [comment] 2016-02-23 19:25
Could this be it - from http://man7.org/linux/man-pages/man7/tcp.7.html?

> tcp_retries2 (integer; default: 15; since Linux 2.2)
              The maximum number of times a TCP packet is retransmitted in
              established state before giving up.  The default value is 15,
              which corresponds to a duration of approximately between **13 to
              30 minutes**, depending on the retransmission timeout.  The
              RFC 1122 specified minimum limit of 100 seconds is typically
              deemed too short.

**Comment by markunsworth** [comment] 2016-02-29 14:51
Is there a way to set a publish timeout on the pika client? So if there's no response from the broker we throw timeout/disconnect exception?

**Comment by vitaly-krugl** [comment] 2016-02-29 20:37
No publish timeout in pika. A more practical feature might be to set up TCP keep-alive on the socket (not just turn it on, but also configure the number of retries and period between retries). I was thinking of adding such a feature. Would you mind trailblazing it?

**Comment by vitaly-krugl** [comment] 2018-03-03 01:46
@markunsworth, the AMQP heartbeat is intended to address this condition. If no traffic is received from RabbitMQ within the specified heartbeat timeout, then the connection needs to be torn down.

I believe I have root-caused the problem. Upon detection of heartbeat timeout, instead of terminating the connection (essentially closing the socket), HearbeatChecker [initiates graceful AMQP connection-close](https://github.com/pika/pika/blob/43936088e1183ec5902f2ba2992c902e87f5460b/pika/heartbeat.py#L122), including a few pikaisms :) inside `Connection.close` (gracefully closing channels, consumers, etc.).

The graceful AMQP connection-close and included actions (graceful closing of channels, etc.) is counter to the purpose of the heartbeat timeout, which is to detect lost connections, and results in a lengthy hang until TCP packet retries are exhausted and the TCP/IP stack eventually concludes (in about 15 to 30 minutes) that the TCP stream is dead.

I think that the following should fix it:
1. Remove the [self._connection.close() call](https://github.com/pika/pika/blob/43936088e1183ec5902f2ba2992c902e87f5460b/pika/heartbeat.py#L122)
2. Leave [self._connection._on_terminate()](https://github.com/pika/pika/blob/43936088e1183ec5902f2ba2992c902e87f5460b/pika/heartbeat.py#L124) in place - it should be sufficient to tear things down.

cc @lukebakken

**Comment by lukebakken** [comment] 2018-03-03 16:06
@markunsworth - if @vitaly-krugl's [comment](https://github.com/pika/pika/issues/708#issuecomment-370105566) does not address your problem, please re-open this issue. Thanks.

**Comment by vitaly-krugl** [comment] 2018-03-03 18:54
@lukebakken, the changes I was referring to in https://github.com/pika/pika/issues/708#issuecomment-370105566 need to be made in Pika, not in user's code. I updated my comment to make this clear and am reopening this issue.

**Comment by vitaly-krugl** [comment] 2018-04-06 07:31
On second thought, I probably goofed with my assessment in https://github.com/pika/pika/issues/708#issuecomment-370105566. Since the heartbeat logic runs in asynchronous code, the `self._connection.close()` call shouldn't block, and the subsequent `_on_terminate()` call drop the connection. So, although `self._connection.close()` is pointless when connection is lost, it's also harmless, and should not be responsible for the hang reported here.

**Comment by markunsworth** [comment] 2018-04-16 10:10
Just an FYI here. I'm no longer at the company where this was an issue so won't be able to feedback on anything. @alvises may be able to help though.

**Comment by vitaly-krugl** [comment] 2018-05-10 09:59
Closing since per @markunsworth's comment https://github.com/pika/pika/issues/708#issuecomment-187124672, he couldn't reproduce the issue once equipment was moved to a private subnet.

**Closed by vitaly-krugl** 2018-05-10 09:59 UTC
