### ISSUE TITLE
KeyError: 'Basic.Ack'

### ISSUE THREAD

**Issue by vadamoto** [pika/pika#463] opened 2014-04-20 11:15 UTC
pika 0.9.14p2
RabbitMQ 3.2.4

Traceback (most recent call last):
  ...
  File ".../src/pika/pika/adapters/blocking_connection.py", line 955, in start_consuming
    self.connection.process_data_events()
  File ".../src/pika/pika/adapters/blocking_connection.py", line 240, in process_data_events
    if self._handle_read():
  File ".../src/pika/pika/adapters/blocking_connection.py", line 348, in _handle_read
    super(BlockingConnection, self)._handle_read()
  File ".../src/pika/pika/adapters/base_connection.py", line 351, in _handle_read
    self._on_data_available(data)
  File ".../src/pika/pika/connection.py", line 1281, in _on_data_available
    self._process_frame(frame_value)
  File ".../src/pika/pika/connection.py", line 1361, in _process_frame
    self._deliver_frame_to_channel(frame_value)
  File ".../src/pika/pika/connection.py", line 972, in _deliver_frame_to_channel
    return self._channels[value.channel_number]._handle_content_frame(value)
  File ".../src/pika/pika/channel.py", line 793, in _handle_content_frame
    self._on_deliver(*response)
  File ".../src/pika/pika/channel.py", line 888, in _on_deliver
    body)
  ... [my callback invoked here] ...
  File ".../src/pika/pika/adapters/blocking_connection.py", line 553, in basic_publish
    (properties, body))
  File ".../src/pika/pika/adapters/blocking_connection.py", line 1144, in _rpc
    return self._process_replies(replies, callback)
  File ".../src/pika/pika/adapters/blocking_connection.py", line 1099, in _process_replies
    frame_value = self._frames[reply]
KeyError: 'Basic.Ack'

**Comment by gmr** [comment] 2015-05-20 00:49
Unfortunately a traceback doesn't do much to help us understand what's going on. Closing due to ticket age and lack of additional context.

**Closed by gmr** 2015-05-20 00:49 UTC

**Comment by hupantingxue** [comment] 2015-09-29 07:49
I met the same question , the pika version is 0.9.13
>>> import pika       
>>> pika.__version__  
'0.9.13' 

and the traceback is below:
> Traceback (most recent call last):                                                                              
>   File "/home/push/v2.1/jpushapi/apiapp/v3/sendutils.py", line 745, in sendmsgToSegment                         
>     mqsnd.send_suc = seg_mq.publish(onepustask_gw)                                                              
>   File "/home/push/v2.1/jpushapi/apiapp/rbmq.py", line 165, in publish                                          
>     ret = self._channel.basic_publish(exchange=self.exc, routing_key=self.rkey, body=body, properties=pika.Basic
> Properties(delivery_mode=2))                                                                                    
>   File "build/bdist.linux-x86_64/egg/pika/adapters/blocking_connection.py", line 521, in basic_publish          
>     (properties, body))                                                                                         
>   File "build/bdist.linux-x86_64/egg/pika/adapters/blocking_connection.py", line 1107, in _rpc                  
>     return self._process_replies(replies, callback)                                                             
>   File "build/bdist.linux-x86_64/egg/pika/adapters/blocking_connection.py", line 1061, in _process_replies      
>     frame_value = self._frames[reply]                                                                           
> KeyError: 'Basic.Ack'

**Comment by vitaly-krugl** [comment] 2015-09-29 16:44
@hupantingxue, please provide **enough** information for someone to **easily** reproduce the issue. Also, please try to reproduce it with the latest release pika version 0.10 and report your findings in a comment here.
