### ISSUE TITLE
Example's on_connection_closed isn't called until ioloop stops

### ISSUE THREAD

**Issue by joshpurvis** [pika/pika#762] opened 2016-07-06 21:20 UTC
We've been experiencing short network glitches which are disrupting our async consumers. Basically they seem to fall in a disconnected state, but they don't output any logs or any other indication, other than they are missing from the RMQ management console, and are no longer processing messages.

In attempts to debug the issue, I copied the example asynchronous consumer from http://pika.readthedocs.io/en/0.10.0/examples/asynchronous_consumer_example.html verbatim. 

Ran it, then disabled port 5672 on my firewall to simulate a network failure. The example consumer also seems to exhibit the same behavior as our code. 

On further testing, I realized that when the process exits, that is `example.stop()` is called, the `on_connection_closed` callback is finally triggered. I assume this is because the ioloop has now stopped.

I'm running RabbitMQ 3.6.0 on the server. I've tried the above on both `0.10.0` and the `master` branch, and I'm seeing the same behavior. I've also experimented with various settings such as different socket timeouts, heartbeats/no heartbeats, etc. The behavior is consistent.

Am I missing something? Is the example out of date?

Thanks!

**Comment by xiaopeng163** [comment] 2017-05-09 08:50
Hi, the same issue, have you resolved that?

**Comment by joshpurvis** [comment] 2017-05-09 13:31
Nope, sorry. I ended up moving all instances off of AWS us-east-1a to a less noisy datacenter and added alerts to detect when queues silently drop (using sensu). I've been experiencing the problem much less frequently, and sensu alerts me when it happens.

**Comment by xiaopeng163** [comment] 2017-05-09 13:45
OK, got it. maybe I should add some code to do auto reconnection when the connection is refused.

**Comment by mlmarius** [comment] 2017-06-27 18:32
i second this issue. seems pretty serious. it can be killed by network outage.

**Comment by mlmarius** [comment] 2017-06-27 18:36
I second this. How can it be fixed when using the async consumer example ?

**Comment by vitaly-krugl** [comment] 2017-06-27 20:42
The async examples were not in a good shape. I refactored the async publisher example via this pull request: #710. That addressed a number of problems like the one reported here. Perhaps someone can refactor the async consumer example along the same lines as #710.

**Comment by vitaly-krugl** [comment] 2017-06-27 21:21
When TCP/IP is trying to transmit on a failed network or to a downed peer, the local tcp/ip stack will eventually detect the problem and place the local socket in a failed state once all the retries are exhausted without an ACK from remote.

However, when just waiting to receive something, such as a message from Rabbit MQ, no retries are involved on the receiving end, so the TCP/IP stack can't  tell on its (by default) that the other peer is unreachable.

If you have AMQP heartbeats enabled, then heartbeat messages will be sent on the socket connection per negotiated AMQP heartbeat configuration. Again, when the remote peer is unreachable for any reason, the TCP/IP retries of the heartbeat message will eventually be exhausted, and the local socket will be placed in a failed state.

At the TCP/IP level, there is a thing known as TCP Keepalive. This may be configured independently of AMQP heartbeats - directly on the connection's socket (Pika doesn't provide an API for this yet) via socket options. When TCP Keepalive is enabled on the socket, the local TCP/IP stack will periodically send keepalive messages to the remote peer's TCP/IP stack on the same socket. When the configured TCP keepalive retries are exhausted, the local TCP/IP stack will place the local socket in the failed state, similarly to what happens when sending regular data and retransmissions are exhausted. See https://en.wikipedia.org/wiki/Keepalive and http://tldp.org/HOWTO/TCP-Keepalive-HOWTO/overview.html.

**Comment by joshpurvis** [comment] 2017-07-26 15:17
@vitaly-krugl 

I'm slightly confused by your last message. Does it imply that the consumer can't be fixed as you did for the publisher examples?

I actually ran into this problem again earlier today. We have some long running python processes that use pika (in a consumer style setup). The queues for a number of these vanished from the Rabbitmq panel, but the processes are still hanging without errors. I suspect this was caused by a network glitch, but oddly not all of the processes failed. If I restart these, they'll be fine.

As an aside: I have AMQP heartbeats set to 60 and TCP keep alive is 7200. It's been longer than 2 hours and they're still hanging. So these settings don't seem to help the situation.

**Comment by lukebakken** [comment] 2018-01-31 21:44
Closing because I can't seem to reproduce:

* Start RabbitMQ 3.7.2 / Erlang 20.2.2
* Start `consumer.py` - [consumer.py.txt](https://github.com/pika/pika/files/1683420/consumer.py.txt)
* Block port 5672 - `sufo nft -f ./nftables-block-5672.conf` - [nftables-block-5672.conf.txt](https://github.com/pika/pika/files/1683422/nftables-block-5672.conf.txt)
* Observe output - [transcript.txt](https://github.com/pika/pika/files/1683424/transcript.txt)

```
DEBUG      2018-01-31 13:35:20,472 pika.callback                  process                              220 : Processing 0:_on_connection_closed
DEBUG      2018-01-31 13:35:20,473 pika.callback                  process                              234 : Calling <bound method ExampleConsumer.on_connection_closed of <__main__.ExampleConsumer object at 0x7fb1679578d0>> for "0:_on_connection_closed"
WARNING    2018-01-31 13:35:20,473 __main__                       on_connection_closed                 90  : Connection closed, reopening in 5 seconds: (-1) ConnectionResetError(104, 'Connection reset by peer')
```

**Closed by lukebakken** 2018-01-31 21:44 UTC
