### ISSUE TITLE
connection created by BlockingConnection()  close blocked

### ISSUE THREAD

**Issue by hoverzheng** [pika/pika#661] opened 2015-10-28 12:01 UTC
hello all:

I used connection = pika.BlockingConnection(conn_params) created connection, and got some channel, then closed channel
when I used connection.close() the programe blocked.
I use tcpdump catch tcp/ip package in rabbitmq server point, can't catch any thing.

What's possible question?
Thanks!

**Comment by vitaly-krugl** [comment] 2015-10-28 16:01
@hoverzheng, please provide additional information that could be helpful for understanding the problem, such as version of pika, operating system where the problem occurred, whether the problem is easily reproducible, a complete code sample to reproduce the problem, whether you made specific changes in RabbitMQ configuration, your (non-confidential) connection parameters, anything else that might be helpful.

If you can reproduce the hang by running your script from the terminal, then once it hangs you might be able to use CTL-C to interrupt the program and get a traceback of where it was blocked. That traceback would be handy to have here.

**Comment by hoverzheng** [comment] 2015-10-30 09:02
Thank you @vitaly-krugl ! 
I try traceback firstly!

**Comment by vmarkovtsev** [comment] 2015-11-02 10:49
This happens to me as well.

```
connection.close()
  File "pika/adapters/blocking_connection.py", line 629, in close
    self._flush_output(self._closed_result.is_ready)
  File "pika/adapters/blocking_connection.py", line 410, in _flush_output
    self._impl.ioloop.poll()
  File "pika/adapters/select_connection.py", line 590, in poll
    events = self._poll.poll(self.get_next_deadline())
KeyboardInterrupt
```

**Comment by heg-hpo** [comment] 2015-11-06 08:55
I am also able to reproduce the issue. Unfortunately, I can't provide any example code but I will try to describe the circumstances and precisely as possible:

I am using pika 0.10.0 installed via pip with python 2.7.9 on Debian jessie x86_64 and recently came across a use case that required using several connections to rabbitmq in a single application. The code is mostly based on the rabbitmq tutorial found on https://www.rabbitmq.com/tutorials/tutorial-one-python.html . Since I need to open multiple connections, I'm starting the channel.start_consuming() method in a separate thread.

This way I create several (might be as little as 3, using more just makes the issue more likely to occur) connections to the rabbitmq server. My example code then just uses time.sleep to wait a few seconds and then begins closing all the connections again with connection.close(). This works most of the time but (with 3 connections) approximately every second time I run the code, one of the connections fails to close.

I dug through the code for several hours and only got as far as the I/O loop. In the connections that fail to shut down is_done() always returns False so the completion condition is never satisfied and the loop keeps running until some terminates the application manually. I don't understand why that happens but my guess would be that the issue is with the last condition in the lambda respectively the fact that ready() keeps returning False.

**Comment by heg-hpo** [comment] 2015-11-06 10:50
@hoverzheng @vmarkovtsev It might be interesting to compare the circumstances in which you and me ran into this issue. Are you using threads in any way or are you creating and closing the connection directly from your main thread?

**Comment by vmarkovtsev** [comment] 2015-11-07 05:06
@heg-hpo I am using a separate thread to basic_consume() and close connection from the main thread.

**Comment by vitaly-krugl** [comment] 2015-11-09 05:47
@vmarkovtsev, you just provided the key information for solving this issue. You said you use one thread to basic_consume and another to close the connection. `pika` is not thread-safe at all; accessing the same pika connection  from multiple threads will result in precisely the type of issue that you're having.

**Comment by vmarkovtsev** [comment] 2015-11-09 16:48
Ok, thanks for pointing this out. Is there any way to forcefully close connection from the right thread? I mean, basic_consume() blocks the thread, so there is no direct way to call close() in it...

**Comment by vitaly-krugl** [comment] 2015-11-09 17:43
@vmarkovtsev: I can't think of any safe way that doesn't involve polling. In the past, I used to deal with this by setting up a timer via the connection, and every time that the timer fires, the code would check a flag and raise an exception if the flag was set. This exception would break out from `start_consuming`.

If your app only needs to consume from a single queue, then you can use the `BlockingChannel.consume(...)` method instead of `basic_consume + start_consuming`. Starting with pika v0.10.0, the `consume` method has an additional arg `inactivity_timeout` that you can make use of for polling. See https://github.com/pika/pika/blob/87d41009cd53a529939a508a41f5f7e148d0b729/pika/adapters/blocking_connection.py#L1698 and the docstring below.

**Comment by vitaly-krugl** [comment] 2015-11-09 17:44
@hoverzheng: are you also using multiple threads to interact with a pika connection?

**Comment by heg-hpo** [comment] 2015-11-13 10:58
@vmarkovtsev: You might also want  to look into the twisted connection adapter. At least for my use case it turned out that it could be much easier (and probably also more efficiently) be solved by using twisted instead of starting dozens of threads with one connection each.

**Comment by vitaly-krugl** [comment] 2015-11-13 17:47
That's a good point - if your code lends itself well to cooperative multitasking, then one of the other adapters could do the trick.

**Comment by hoverzheng** [comment] 2015-12-07 08:57
Thank you ,I used threads. but used two connection, every thread had its connection.
I found it blocking connection.close() function.
I solve it using: remove connection.close() function, And When exception happend, I close the connection.

**Comment by vmarkovtsev** [comment] 2015-12-07 16:10
Thanks for advice, but nah, I am using Django.

**Comment by vitaly-krugl** [comment] 2015-12-07 17:51
I would like to help resolve the hang issue, but the information provided is not sufficient for it. Many of the BlockingConnection tests create/close channels and close connections, and the tests don't hang; thus, I am at a loss.

CC @gmr

**Comment by vmarkovtsev** [comment] 2015-12-08 12:02
I've used [gmr/rabbitpy](https://github.com/gmr/rabbitpy) and it appeared to be almost a drop-in replacement. It does not have this issue (it is you who run the event loop thread)

**Comment by vitaly-krugl** [comment] 2016-02-06 18:50
Closing issue since sharing of a connection by multiple threads is officially not supported by the API.

**Closed** 2016-02-06 18:50 UTC
