### ISSUE TITLE
callback of queue_declare is not calls sometimes (but queues are really declared)

### ISSUE THREAD

**Issue by morden2k** [pika/pika#652] opened 2015-10-08 15:55 UTC
I do not have correct callbacks for queues without names (I generates uniques names by RabbitMQ server for temporary replies queue in my RPC). I need this for know queue names which generates (currently I manually generates they since I have this issue) server for bind to they afterwards. In async model how I understand I kan know this anly from queue_declare callback.

Let's get official example for asyc consumer (SelectConnection addapter):
http://pika.readthedocs.org/en/latest/examples/asynchronous_consumer_example.html

Let's change on_exchange_declareok and on_queue_declareok to:

    def on_exchange_declareok(self, unused_frame):
        """Invoked by pika when RabbitMQ has finished the Exchange.Declare RPC
        command.

        :param pika.Frame.Method unused_frame: Exchange.DeclareOk response frame

        """
        LOGGER.info('Exchange declared')
        # self.setup_queue(self.QUEUE)

        self._channel.queue_declare(self.on_queue_declareok, 'test1')
        self._channel.queue_declare(self.on_queue_declareok, 'test2')
        self._channel.queue_declare(self.on_queue_declareok, 'test3')
        self._channel.queue_declare(self.on_queue_declareok, 'test4')
        self._channel.queue_declare(self.on_queue_declareok, 'test5')
        self._channel.queue_declare(self.on_queue_declareok, 'test6')

    def on_queue_declareok(self, method_frame):
        """Method invoked by pika when the Queue.Declare RPC call made in
        setup_queue has completed. In this method we will bind the queue
        and exchange together with the routing key by issuing the Queue.Bind
        RPC command. When this command is complete, the on_bindok method will
        be invoked by pika.

        :param pika.frame.Method method_frame: The Queue.DeclareOk frame

        """
        LOGGER.info('Binding %s to %s with %s',
                    self.EXCHANGE, self.QUEUE, self.ROUTING_KEY)

        print 'queue: ' + method_frame.method.queue
        pass
        # self._channel.queue_bind(self.on_bindok, self.QUEUE,
        #                          self.EXCHANGE, self.ROUTING_KEY)

Result:

    queue: test1
    queue: test2
    queue: test3
    queue: test4
    queue: test5
    queue: test6

All is ok. Now let's change on_exchange_declareok to:

    self._channel.queue_declare(self.on_queue_declareok)
    self._channel.queue_declare(self.on_queue_declareok)
    self._channel.queue_declare(self.on_queue_declareok)
    self._channel.queue_declare(self.on_queue_declareok)
    self._channel.queue_declare(self.on_queue_declareok)
    self._channel.queue_declare(self.on_queue_declareok)

Result:

    queue: amq.gen-dcZ3p952t4pEPo7cp8LSZg
    queue: amq.gen-fITYyC1VKZMe6a0P6gqmsw
    queue: amq.gen-Qf6guwM6d-s3CCETcfEDCw
    queue: amq.gen--QtK7cJNMcy3xwOMg43B4Q
    queue: amq.gen-j_ticywsvBosnHUpmpfkfg
    queue: amq.gen-qaYLdstEyhXI0IZrH1W9Aw

All is ok. And now let's change on_exchange_declareok to:

    self._channel.queue_declare(self.on_queue_declareok)
    self._channel.queue_declare(self.on_queue_declareok)
    self._channel.queue_declare(self.on_queue_declareok)
    self._channel.queue_declare(self.on_queue_declareok, 'test1')
    self._channel.queue_declare(self.on_queue_declareok, 'test2')
    self._channel.queue_declare(self.on_queue_declareok, 'test3')
    self._channel.queue_declare(self.on_queue_declareok)
    self._channel.queue_declare(self.on_queue_declareok)
    self._channel.queue_declare(self.on_queue_declareok)
    self._channel.queue_declare(self.on_queue_declareok, 'test4')
    self._channel.queue_declare(self.on_queue_declareok, 'test5')
    self._channel.queue_declare(self.on_queue_declareok, 'test6')

Result:

    queue: amq.gen-WT7U62w2csAvFCcGxI3bhg
    queue: amq.gen-KwhGNO_ulcw9_dl1Y5a42w
    queue: amq.gen-zBK7YeOAjHwebwrHty7k_w
    queue: test1
    queue: test1
    queue: test2
    queue: test3
    queue: test4
    queue: test5
    queue: test6

**Where is my 3 temporary queues?** On server side all is ok. I have all my 12 queus (6 with predefined names and 6 with generated names) so real issue in pika library

Also:

    self._channel.queue_declare(self.on_queue_declareok)
    self._channel.queue_declare(self.on_queue_declareok, 'test1')
    self._channel.queue_declare(self.on_queue_declareok)
    self._channel.queue_declare(self.on_queue_declareok, 'test2')
    self._channel.queue_declare(self.on_queue_declareok)
    self._channel.queue_declare(self.on_queue_declareok, 'test3')
    self._channel.queue_declare(self.on_queue_declareok)
    self._channel.queue_declare(self.on_queue_declareok, 'test3')
    self._channel.queue_declare(self.on_queue_declareok)
    self._channel.queue_declare(self.on_queue_declareok, 'test4')
    self._channel.queue_declare(self.on_queue_declareok)
    self._channel.queue_declare(self.on_queue_declareok, 'test5')
    self._channel.queue_declare(self.on_queue_declareok)
    self._channel.queue_declare(self.on_queue_declareok, 'test6')

Result:

    queue: amq.gen-OYOxxVnWjsJZy90NmQFyiw
    queue: test1
    queue: test1
    queue: test2
    queue: test3
    queue: test3
    queue: test4
    queue: test5
    queue: test6

**test1 and test3 was duplicated**

P.S. In case when queues with name-generating setupped first all is ok:

    self._channel.queue_declare(self.on_queue_declareok)
    self._channel.queue_declare(self.on_queue_declareok)
    self._channel.queue_declare(self.on_queue_declareok)
    self._channel.queue_declare(self.on_queue_declareok)
    self._channel.queue_declare(self.on_queue_declareok)
    self._channel.queue_declare(self.on_queue_declareok)
    self._channel.queue_declare(self.on_queue_declareok, 'test1')
    self._channel.queue_declare(self.on_queue_declareok, 'test2')
    self._channel.queue_declare(self.on_queue_declareok, 'test3')
    self._channel.queue_declare(self.on_queue_declareok, 'test4')
    self._channel.queue_declare(self.on_queue_declareok, 'test5')
    self._channel.queue_declare(self.on_queue_declareok, 'test6')

Result:

    queue: amq.gen-_GhRhpnE07QulTQKNrFz7g
    queue: amq.gen-ineC-bI1Q-9_yUSxUO6Trg
    queue: amq.gen-O2Oexx8yOfWtexTjGo1AIA
    queue: amq.gen-mjMfSTW2Q-wfNGQGOK7s1A
    queue: amq.gen-Z6PtZZo551ymRJTfoRjDXw
    queue: amq.gen-gMOT0Q3CaeZDhU9KbZ1rcw
    queue: test1
    queue: test2
    queue: test3
    queue: test4
    queue: test5
    queue: test6

So **temorary workarrounds** of this issue are next:
1) declare queues without names (with auto-generating names) before queues with names
or
2) generate all unique names for temporary queues manually, e.g.: 'tmp_' + str(uuid.uuid4())

**Comment by vitaly-krugl** [comment] 2016-02-28 00:01
Unable to reproduce with pika 0.10.0 with the following changes in example:

```
    def on_exchange_declareok(self, unused_frame):
        """Invoked by pika when RabbitMQ has finished the Exchange.Declare RPC
        command.

        :param pika.Frame.Method unused_frame: Exchange.DeclareOk response frame

        """
        LOGGER.info('Exchange declared')
        # self.setup_queue(self.QUEUE)

        self._channel.queue_declare(self.on_queue_declareok)
        self._channel.queue_declare(self.on_queue_declareok)
        self._channel.queue_declare(self.on_queue_declareok)
        self._channel.queue_declare(self.on_queue_declareok, 'test1')
        self._channel.queue_declare(self.on_queue_declareok, 'test2')
        self._channel.queue_declare(self.on_queue_declareok, 'test3')
        self._channel.queue_declare(self.on_queue_declareok)
        self._channel.queue_declare(self.on_queue_declareok)
        self._channel.queue_declare(self.on_queue_declareok)
        self._channel.queue_declare(self.on_queue_declareok, 'test4')
        self._channel.queue_declare(self.on_queue_declareok, 'test5')
        self._channel.queue_declare(self.on_queue_declareok, 'test6')

##    def setup_queue(self, queue_name):
##        """Setup the queue on RabbitMQ by invoking the Queue.Declare RPC
##        command. When it is complete, the on_queue_declareok method will
##        be invoked by pika.
##
##        :param str|unicode queue_name: The name of the queue to declare.
##
##        """
##        LOGGER.info('Declaring queue %s', queue_name)
##        self._channel.queue_declare(self.on_queue_declareok, queue_name)

    def on_queue_declareok(self, method_frame):
        """Method invoked by pika when the Queue.Declare RPC call made in
        setup_queue has completed. In this method we will bind the queue
        and exchange together with the routing key by issuing the Queue.Bind
        RPC command. When this command is complete, the on_bindok method will
        be invoked by pika.

        :param pika.frame.Method method_frame: The Queue.DeclareOk frame

        """
##        LOGGER.info('Binding %s to %s with %s',
##                    self.EXCHANGE, self.QUEUE, self.ROUTING_KEY)

        print 'queue: ' + method_frame.method.queue
        pass
        # self._channel.queue_bind(self.on_bindok, self.QUEUE,
        #                          self.EXCHANGE, self.ROUTING_KEY)
```

Get this output:

```
$ python pika652nodeclareok.py 
INFO       2016-02-27 15:59:08,359 __main__                       connect                              50  : Connecting to amqp://guest:guest@localhost:5672/%2F
INFO       2016-02-27 15:59:08,361 pika.adapters.base_connection  _create_and_connect_to_socket        212 : Connecting to 127.0.0.1:5672
INFO       2016-02-27 15:59:08,364 __main__                       on_connection_open                   63  : Connection opened
INFO       2016-02-27 15:59:08,364 __main__                       add_on_connection_close_callback     72  : Adding connection close callback
INFO       2016-02-27 15:59:08,364 __main__                       open_channel                         115 : Creating a new channel
INFO       2016-02-27 15:59:08,365 __main__                       on_channel_open                      127 : Channel opened
INFO       2016-02-27 15:59:08,365 __main__                       add_on_channel_close_callback        137 : Adding channel close callback
INFO       2016-02-27 15:59:08,365 __main__                       setup_exchange                       164 : Declaring exchange message
INFO       2016-02-27 15:59:08,366 __main__                       on_exchange_declareok                176 : Exchange declared
queue: amq.gen-JjeEbuyVnPwmvuzapRi4Vw
queue: amq.gen-tVv6HrC0PUptYGlioQqekw
queue: amq.gen-1QZm6eIitGT-vdtA5YqZaA
queue: test1
queue: test2
queue: test3
queue: amq.gen-TzN09hNaGweAM2WZNClmGQ
queue: amq.gen-1VS81hd8VBcf89qfS4tWzQ
queue: amq.gen-uV5PuRvBKvv-cNnvDmnlFA
queue: test4
queue: test5
queue: test6
```

**Comment by vitaly-krugl** [comment] 2016-02-28 00:03
Also, can't reproduce with this change:

```
self._channel.queue_declare(self.on_queue_declareok)
self._channel.queue_declare(self.on_queue_declareok, 'test1')
self._channel.queue_declare(self.on_queue_declareok)
self._channel.queue_declare(self.on_queue_declareok, 'test2')
self._channel.queue_declare(self.on_queue_declareok)
self._channel.queue_declare(self.on_queue_declareok, 'test3')
self._channel.queue_declare(self.on_queue_declareok)
self._channel.queue_declare(self.on_queue_declareok, 'test3')
self._channel.queue_declare(self.on_queue_declareok)
self._channel.queue_declare(self.on_queue_declareok, 'test4')
self._channel.queue_declare(self.on_queue_declareok)
self._channel.queue_declare(self.on_queue_declareok, 'test5')
self._channel.queue_declare(self.on_queue_declareok)
self._channel.queue_declare(self.on_queue_declareok, 'test6')
```
The output is 
```
$ python pika652nodeclareok.py 
INFO       2016-02-27 16:02:40,209 __main__                       connect                              50  : Connecting to amqp://guest:guest@localhost:5672/%2F
INFO       2016-02-27 16:02:41,344 pika.adapters.base_connection  _create_and_connect_to_socket        212 : Connecting to 127.0.0.1:5672
INFO       2016-02-27 16:02:42,470 __main__                       on_connection_open                   63  : Connection opened
INFO       2016-02-27 16:02:42,471 __main__                       add_on_connection_close_callback     72  : Adding connection close callback
INFO       2016-02-27 16:02:42,471 __main__                       open_channel                         115 : Creating a new channel
INFO       2016-02-27 16:02:42,472 __main__                       on_channel_open                      127 : Channel opened
INFO       2016-02-27 16:02:42,472 __main__                       add_on_channel_close_callback        137 : Adding channel close callback
INFO       2016-02-27 16:02:42,472 __main__                       setup_exchange                       164 : Declaring exchange message
INFO       2016-02-27 16:02:42,473 __main__                       on_exchange_declareok                176 : Exchange declared
queue: amq.gen-_p16zykolDtjz0tgHGKDbg
queue: test1
queue: amq.gen-8fkknVZw1Bzi-_dQmHZVzw
queue: test2
queue: amq.gen-pxtQnebsRRKcjMcxNgWAmg
queue: test3
queue: amq.gen-bZoQv7uFT6-Mi85fSeKhiA
queue: test3
queue: amq.gen-qOK-FmSkqKWTsqQTXtf0yA
queue: test4
queue: amq.gen-N1PQoV7h5dEOHBr3FHqDrA
queue: test5
queue: amq.gen-FSQfhxjLmawC4qDZQtTcPg
queue: test6
```

**Comment by vitaly-krugl** [comment] 2016-02-28 00:08
@morden2k, I was unable to reproduce this issue against pika 0.10.0 running on Mac OS X El Capitan and python 2.7.10. I am closing this issue. For your reference, I published a gist of my test script at https://gist.github.com/vitaly-krugl/2243c86c24709cebf500. Please try it against the pika 0.10.0 and against Pika master and open a new issue if you can still reproduce it.

**Closed by vitaly-krugl** 2016-02-28 00:08 UTC
