### ISSUE TITLE
BlockingConnection cause timeout exception in docker under Ubuntu 15

### ISSUE THREAD

**Issue by bobcyw** [pika/pika#635] opened 2015-08-10 16:14 UTC
The environment is a docker container, the container looks like
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty
```
this is container's python version
```
Python 3.4.0 (default, Jun 19 2015, 14:20:21) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
```
and the real os is
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.04
Release:        15.04
Codename:       vivid
```
This exception only raise when dockerfile call the module
```
CMD python3 -m maintenance.rss.fenci_worker
```
When I attach the docker container and run it by manual it's ok. And when I use another real os
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.10
Release:        14.10
Codename:       utopic
```
and the same docker container, manual or use
```
CMD python3 -m maintenance.rss.fenci_worker
```
is always ok. 
This is the exception.
```
2015-08-10T15:30:51.692860089Z Traceback (most recent call last):
2015-08-10T15:30:51.692961820Z   File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
2015-08-10T15:30:51.692976406Z     "__main__", mod_spec)
2015-08-10T15:30:51.692987517Z   File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
2015-08-10T15:30:51.692997734Z     exec(code, run_globals)
2015-08-10T15:30:51.693007864Z   File "/code/weixin/maintenance/rss/fenci_worker.py", line 12, in <module>
2015-08-10T15:30:51.693018784Z     host='192.168.1.80'))
2015-08-10T15:30:51.693030548Z   File "/usr/local/lib/python3.4/dist-packages/pika/adapters/blocking_connection.py", line 130, in __init__
2015-08-10T15:30:51.693041479Z     super(BlockingConnection, self).__init__(parameters, None, False)
2015-08-10T15:30:51.693051739Z   File "/usr/local/lib/python3.4/dist-packages/pika/adapters/base_connection.py", line 72, in __init__
2015-08-10T15:30:51.693062070Z     on_close_callback)
2015-08-10T15:30:51.693072337Z   File "/usr/local/lib/python3.4/dist-packages/pika/connection.py", line 596, in __init__
2015-08-10T15:30:51.693082730Z     self.connect()
2015-08-10T15:30:51.693092720Z   File "/usr/local/lib/python3.4/dist-packages/pika/adapters/blocking_connection.py", line 230, in connect
2015-08-10T15:30:51.693103093Z     error = self._adapter_connect()
2015-08-10T15:30:51.693131632Z   File "/usr/local/lib/python3.4/dist-packages/pika/adapters/blocking_connection.py", line 301, in _adapter_connect
2015-08-10T15:30:51.693142273Z     raise exceptions.AMQPConnectionError(error)
2015-08-10T15:30:51.693151867Z pika.exceptions.AMQPConnectionError: Connection to 192.168.1.80:5672 failed: timeout
```
This is module's source code
```
__author__ = 'caoyawen'
import pika
from bson import json_util
import json
from maintenance.rss.fenci import handle_one_rss_data
from maintenance.rss.mongo_op import weixin

rss = weixin.rss

connection = pika.BlockingConnection(pika.ConnectionParameters(
               host='192.168.1.80'))
channel = connection.channel()
channel.queue_declare(queue='fenci')


def callback(ch, method, properties, body:bytes):
    one_page = json.loads(body.decode("utf-8"), object_hook=json_util.object_hook)
    # pp(one_page)
    page_data = rss.find_one({"_id": one_page["id"]})
    # pp(page_data)
    if page_data is not None:
        handle_one_rss_data((page_data, one_page["index"], one_page["total"]))
    else:
        raise Exception("id is not exit")
    # print("handle complete")
    ch.basic_ack(delivery_tag = method.delivery_tag)
    # print(" [x] Received %r" % (body,))

channel.basic_qos(prefetch_count=1)
channel.basic_consume(callback,
                      queue='fenci',)

channel.start_consuming()
```

**Comment by gmr** [comment] 2015-08-10 17:14
Per the exception, you're having some sort of network related problem connecting to RabbitMQ:

```
 pika.exceptions.AMQPConnectionError: Connection to 192.168.1.80:5672 failed: timeout
```

That means the socket timed out connecting to 192.168.1.80 on port 5672.

**Comment by vitaly-krugl** [comment] 2015-08-10 17:34
@bobcyw, the traceback that you provided suggests that you're using pika 0.9.14 or older with Python 3.x. Python 3.x compatibility was added in pika 0.10.0, which is presently available as a pre-release on PyPi. I install the pre-release on my system using `pip install pika --pre`.

**Comment by bobcyw** [comment] 2015-08-10 22:49
@gmr ,I run rabbitmq also in a dock container. It looks like that
```
docker run -p 5672:5672 -d --hostname my-rabbit --name some-rabbit rabbitmq
```
it is a little different from office command line (https://hub.docker.com/_/rabbitmq/)
```
docker run -d --hostname my-rabbit --name some-rabbit rabbitmq:3-management
```
and this is container description
```
e4b4034dcd84    rabbitmq    "/docker-entrypoint.   7 hours ago    Up 7 hours    0.0.0.0:5672->5672/tcp  some-rabbit
```
Is port mapping cause this exception? Because there's no 5672/UDP port mapping.

@vitaly-krugl thank you for your suggestion, I'll try ```pip install pika --pre```.

**Comment by gmr** [comment] 2015-08-11 02:36
RabbitMQ does not listen on 5672/UDP by default. It should be -p 5672:5672 in your docker run.

**Comment by bobcyw** [comment] 2015-08-11 06:58
@gmr The same module is ok on my MacBook with the same RabbitMQ IP addr. 5 workers are running over 12 hours. And it's also ok when typing ``` python3 -m maintenance.rss.fenci_worker ``` in the dock container's console.

**Comment by gmr** [comment] 2015-08-11 13:13
Ok, but the issue is clearly that your app can't connect to RabbitMQ. I'm not sure how to help you troubleshoot beyond that. Have you tried connecting to the RabbitMQ instance running in the container from anything/anywhere else?

**Comment by bobcyw** [comment] 2015-08-16 19:05
It seems ok when container's host os is Ubuntu 14.04. This exception only occours when container's host os is Ubuntu 15.04

**Comment by gmr** [comment] 2015-08-17 14:23
No it's not -- the exception is pretty clear that your app can not connect to RabbitMQ -- that is the only issue that can be divined from the information provided.

**Comment by vitaly-krugl** [comment] 2015-08-17 22:49
I concur with @gmr

**Comment by vitaly-krugl** [comment] 2016-02-27 23:21
Appears to be user error in docker/network configuration. Closing.

**Closed by vitaly-krugl** 2016-02-27 23:21 UTC
