### ISSUE TITLE
Connection gets closed due to missed heartbeats

### ISSUE THREAD

**Issue by chnandu** [pika/pika#1104] opened 2018-07-24 00:48 UTC
Hi,

We are currently seeing an issue with our application which uses pika to send/consume messages to/from Rabbit MQ. I don't think it is a bug but we are certainly missing something here so wanted to get some help or feedback from this forum. 

We are using pika 0.11.2 and Rabbit 3.7.4.
We recently upgraded both pika & Rabbit and since then we started seeing an issue with our application so not sure what else need to be changed.
Also, we are using SelectConnection for sending or consuming messages in and out of Rabbit MQ.
When sending messages after opening a connection, at times, our application can do some processing in between sending messages so it doesn't queue in a message until after few minutes from the last message sent. 
Issue is when that happens we are seeing the Rabbit is closing the connection with the following error in its log:
"missed heartbeats from client, timeout: 60s"

From tcpdump, it appears, Rabbit server is sending a heartbeat(not sure) frame every 60 secs and I see a reply back immediately. But after 2 attempts, I do not see a reply and that's exactly when I see the error message in Rabbit logs.

We have 'heartbeat' set to None when initiating SelectConnection object. And Rabbit is using all default configurations, nothing has been changed by us.

Here is tcpdump output:

sudo tcpdump -i lo port 54436
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on lo, link-type EN10MB (Ethernet), capture size 65535 bytes
18:44:28.797612 IP localhost.amqp > localhost.54436: Flags [P.], seq 1356704746:1356704754, ack 2440025265, win 32779, options [nop,nop,TS val 668711718 ecr 668696729], length 8
18:44:28.797639 IP localhost.54436 > localhost.amqp: Flags [.], ack 8, win 350, options [nop,nop,TS val 668711718 ecr 668711718], length 0
18:45:28.799615 IP localhost.amqp > localhost.54436: Flags [P.], seq 8:16, ack 1, win 32779, options [nop,nop,TS val 668726718 ecr 668711718], length 8
18:45:28.799645 IP localhost.54436 > localhost.amqp: Flags [.], ack 16, win 350, options [nop,nop,TS val 668726718 ecr 668726718], length 0
18:46:28.798834 IP localhost.amqp > localhost.54436: Flags [R.], seq 16, ack 1, win 32779, options [nop,nop,TS val 668741718 ecr 668726718], length 0

In above instance, connection was opened at 18:43:28, last successful message was sent at 18:43:48. It took me few to start the tcpdump after opening the connection so it could capture the packets only from 18:44:28.
At 18:46:28, there was no reply back to the server, I am not sure what that means but that caused the connection to be closed by the server.
In the Rabbit logs:
2018-07-23 18:46:28.798 [warning] <0.11822.4> closing AMQP connection <0.11822.4> (127.0.0.1:54436 -> 127.0.0.1:5672):
missed heartbeats from client, timeout: 60s

Questions are -
- From https://www.rabbitmq.com/heartbeats.html#heartbeats-timeout, "Heartbeat frames are sent about every timeout / 2 seconds. ". But in our case, I do not see any traffic at 60/2=30sec interval but the traffic is seen only at 60 sec interval. Is there something that need to be configured to make it work according to the Rabbit documentation ?
- Also from docs, "After two missed heartbeats, the peer is considered to be unreachable". But it looks in this case, it is closing the connection after one missed heartbeat. Am I correct ?
- Finally, how can we solve this issue ? Is there anything I am missing ?
I'd appreciate the help. Thanks.

**Comment by 0x00evil** [comment] 2018-07-24 10:18
Got the same problem.
I think it's bug.
My solution is let the callback run in another thread and main thread send heartbeat every 5 secs.

import threading

import pika


class Rabbitmq:
    def __init__(self, username, password, host, vhost):
        credentials = pika.PlainCredentials(username=username, password=password)
        connection_parameters = pika.ConnectionParameters(credentials=credentials, host=host, virtual_host=vhost)
        connection = pika.BlockingConnection(connection_parameters)
        channel = connection.channel()
        channel.basic_qos(prefetch_count=1)
        self.connection = connection
        self.channel = channel

    def receive(self, queue_name, callback=None):
        """rabbitmq receiver"""

        def cb(ch, method, properties, body):
            if callback is not None:
                t = threading.Thread(target=callback, args=(body,))
                t.daemon = True
                t.start()

                while t.is_alive():
                    print "[INFO] heart beating"
                    self.connection.process_data_events()
                    # safer way to sleep(time.sleep will ignore frames sent from broker
                    self.connection.sleep(5)

            ch.basic_ack(delivery_tag=method.delivery_tag)

        self.channel.basic_consume(cb, queue_name)
        self.channel.start_consuming()

    def send(self, message, exchange, routing_key, delivery_mode=2, priority=None):
        """rabbitmq sender"""
        self.channel.basic_publish(exchange=exchange,
                                   routing_key=routing_key,
                                   body=message,
                                   properties=pika.BasicProperties(delivery_mode=delivery_mode, priority=priority))

    def close(self):
        self.connection.close()

**Comment by chnandu** [comment] 2018-07-25 18:32
@0x00evil Thanks. I can try implementing similar logic using SelectConnection adapter. As of now, we are trying to change our application logic to do the processing outside of sending thread for avoiding the idle periods in between. If it is a bug then it would be nice to have a fix for it.

**Comment by lukebakken** [comment] 2018-07-29 14:13
@0x00evil - it's not a bug. I have been out on vacation and will follow up tomorrow.

@chnandu - please provide your code so I can help out.

In short, you should be using Pika `0.12.0`. If your message processing takes a long time before calling `basic_ack`, you should run the processing in another thread and then use `add_callback_threadsafe` to schedule the `basic_ack` call.

Please see [this example](https://github.com/pika/pika/blob/0.12.0/examples/basic_consumer_threaded.py).

**Comment by chnandu** [comment] 2018-07-31 19:13
Hi @lukebakken, Thanks for looking in to it. I see the 0.12.0 release notes has "Heartbeats are now sent at an interval equal to 1/2 of the negotiated idle connection timeout".  So I guess that resolves the issue because pika sending heartbeats to broker every 1/2 of negotiated idle connection timeout would definitely keep broker from closing the connection prematurely.

I'll upload my code in a day or two. I need to test our code with 0.12.0 version and make a plan to upgrade pika in all our systems. After that I'll upload the code.
We have just upgraded our application to use pika 0.11.2 from 0.9.6, early June. I noticed the version 0.12.0 got released after we finished upgrading our Prod system or at about same time but we didn't think 0.11.2 would cause connections to be closed by broker prematurely. So didn't pay attention to the latest release.

Also, our application is failing even when publishing messages. We implemented logic to reconnect automatically in consumer but we didn't implement the same in publisher so the failures with publishing were obvious. And we haven't disabled the heartbeats.

**Comment by lukebakken** [comment] 2018-08-01 16:55
I'm assuming that `0.12.0` will resolve your issues. If not, please add a comment here.

**Comment by chnandu** [comment] 2018-08-07 02:40
Hi @lukebakken, Unfortunately I am still seeing the issue even with `0.12.0`. I uploaded the code here: https://gist.github.com/chnandu/9d90e8b2cc46f762ee66d3db032832b0.
When sending(or publishing) messages to Rabbit, if there is idle time(>30 secs) between sending messages then Rabbit is closing the connection prematurely.
I also tried adding our send_msg() function as callback using add_threadsafe_callback() but it still not working.
Not sure why Rabbit thinks the client is lost or why pika isn't sending heartbeats... We have worked around this by eliminating the processing of messages once the connection is opened for now, so it is not a pressing issue at the moment but would like to understand what is wrong and what to be changed..
Appreciate your help.

**Comment by yifeikong** [comment] 2018-08-09 03:31
same here, I'm using 0.12.0 and noticed the same issue.

When I stopped publishing messages, and restart publishing messages, and got ChannelClosed Error

**Comment by lukebakken** [comment] 2018-08-09 18:12
@chnandu your code doesn't work without modification using Python 2.7.15 due to missing symbols and such. I'm working on my own version here: https://gist.github.com/lukebakken/b52bf5023bfcb78208a02f56e942a011

I'm pretty confident that this loop is blocking the `SelectConnection`'s ioloop: https://gist.github.com/lukebakken/b52bf5023bfcb78208a02f56e942a011#file-zpika-py-L615-L639

How do I know? The very first `Basic.Publish` AMQP message is never even sent when tracing port `5672` in Wireshark.

As of now, there is no indication of a Pika bug.

**Comment by lukebakken** [comment] 2018-08-09 18:29
@chnandu I have made some basic changes in my gist that keep the SelectConnection ioloop from being blocked. Here is the gist link again:

https://gist.github.com/lukebakken/b52bf5023bfcb78208a02f56e942a011

Since you are polling the message queue in the same thread that is running the `SelectConnection`, the queue polling loop **will block the `SelectConnection`'s ioloop!** If you do this, messages aren't published, heartbeats aren't, sent, and RabbitMQ will close the connection.

Let me know if you have additional questions, but I will close this issue as there is no bug.

@yifeikong you may be running into the same thing.

**Closed by lukebakken** 2018-08-09 18:29 UTC
Labels: Pending Investigation

**Comment by chnandu** [comment] 2018-08-10 21:27
Hi @lukebakken Thanks for looking in to it and for the solution. Didn't realize ioloop is blocked, now I got the answers I am looking for. Thanks again..

**Comment by Jacobh2** [comment] 2018-09-26 13:51
I think I'm also seeing a similar problem to this:

I'm using the `BlockingConnection` and after some time of consuming messages I see a 
```
pika.exceptions.ConnectionClosed: (-1, "ConnectionResetError(104, 'Connection reset by peer')")
```
and the logs of RabbitMQ I see:
```
2018-09-26 12:53:04.114 [warning] <0.8398.0> closing AMQP connection <0.8398.0> (client_sender_1.client_default:40236 -> dc000002c2:5672):
missed heartbeats from client, timeout: 60s
```

How can I ensure that the heartbeat is running?

**Comment by lukebakken** [comment] 2018-09-26 14:42
@Jacobh2 - please don't respond to a closed issue. Instead, provide information on the [`pika-python`](https://groups.google.com/forum/#!forum/pika-python) mailing list, including the following:

* Broker, broker version, if RabbitMQ then Erlang version
* Pika version
* Python version
* Code to reproduce the issue

The two small pieces of information you have provided suggest an issue in your code. Thanks!
