### ISSUE TITLE
Losing connection

### ISSUE THREAD

**Issue by sulsj** [pika/pika#564] opened 2015-05-06 23:49 UTC
Hi, 

I'm using 0.9.14 version pika on RabbitMQ  3.1.5. My application has a client which distributes a set of tasks so that many workers process the tasks. The issue I've been seeing for a long time is the worker always lose it's connection esp. when there are multiple workers are running. Please let me know if this has already been discussed. Here comes the code and the trace. 

Thanks, 
Seung

---
```
def on_request(ch, method, props, body):
    ...
    log.info("Return queue name = %s", props.reply_to)
    ch.basic_publish(exchange='', 
	 routing_key=props.reply_to, 
	 properties=pika.BasicProperties(
   	    delivery_mode = 2,
	    correlation_id = props.correlation_id),
	    body=response)
   
    logger.info("Sent the result back to the client via '%s' queue." % (props.reply_to))
    ch.basic_ack(delivery_tag=method.delivery_tag)
	
...

def main(argv):
    ...
    ch.basic_qos(prefetch_count=1)
    ch.basic_consume(on_request, queue=taskQueueName, no_ack=False)
    ch.start_consuming()
    ...
```

2015-05-06 12:29:34,029 | tfmq-worker | on_request | DEBUG : Return queue name =  after_20150201.csv.tfmq.task.lst_RESULT_QUEUE
 Traceback (most recent call last):
  File "/.../tfmq-worker", line 555, in <module>
    sys.exit(main(sys.argv))
  File "/.../tfmq-worker", line 545, in main
    ch.start_consuming()
  File "/.../python2.7/site-packages/pika/adapters/blocking_connection.py", line 955, in start_consuming
    self.connection.process_data_events()
  File "/.../python2.7/site-packages/pika/adapters/blocking_connection.py", line 240, in process_data_events
    if self._handle_read():
  File "/.../python2.7/site-packages/pika/adapters/blocking_connection.py", line 348, in _handle_read
    super(BlockingConnection, self)._handle_read()
  File "/.../python2.7/site-packages/pika/adapters/base_connection.py", line 351, in _handle_read
    self._on_data_available(data)
  File "/.../python2.7/site-packages/pika/connection.py", line 1285, in _on_data_available
    self._process_frame(frame_value)
  File "/.../python2.7/site-packages/pika/connection.py", line 1365, in _process_frame
    self._deliver_frame_to_channel(frame_value)
  File "/.../python2.7/site-packages/pika/connection.py", line 976, in _deliver_frame_to_channel
    return self._channels[value.channel_number]._handle_content_frame(value)
  File "/.../python2.7/site-packages/pika/channel.py", line 792, in _handle_content_frame
    self._on_deliver(*response)
  File "/.../python2.7/site-packages/pika/channel.py", line 886, in _on_deliver
    body)
  File "/somewhere/tfmq-worker", line 191, in on_request
    body=response)
  File "/.../python2.7/site-packages/pika/adapters/blocking_connection.py", line 572, in basic_publish
    (properties, body), False)
  File "/.../python2.7/site-packages/pika/adapters/blocking_connection.py", line 1159, in _send_method
    self.connection.send_method(self.channel_number, method_frame, content)
  File "/.../python2.7/site-packages/pika/adapters/blocking_connection.py", line 274, in send_method
    self._send_method(channel_number, method_frame, content)
  File "/.../python2.7/site-packages/pika/connection.py", line 1503, in _send_method
    self._send_frame(frame.Method(channel_number, method_frame))
  File "/.../python2.7/site-packages/pika/adapters/blocking_connection.py", line 417, in _send_frame
    super(BlockingConnection, self)._send_frame(frame_value)
  File "/.../python2.7/site-packages/pika/connection.py", line 1490, in _send_frame
    self._flush_outbound()
  File "/.../python2.7/site-packages/pika/adapters/blocking_connection.py", line 377, in _flush_outbound
    if self._handle_write():
  File "/.../python2.7/site-packages/pika/adapters/base_connection.py", line 365, in _handle_write
    return self._handle_error(error)
  File "/.../python2.7/site-packages/pika/adapters/base_connection.py", line 302, in _handle_error
    self._handle_disconnect()
  File "/.../python2.7/site-packages/pika/adapters/base_connection.py", line 248, in _handle_disconnect
    self._adapter_disconnect()
  File "/.../python2.7/site-packages/pika/adapters/blocking_connection.py", line 318, in _adapter_disconnect
    self._check_state_on_disconnect()
  File "/.../python2.7/site-packages/pika/adapters/blocking_connection.py", line 371, in _check_state_on_disconnect
    raise exceptions.ConnectionClosed()
pika.exceptions.ConnectionClosed

**Comment by wjps** [comment] 2015-05-07 06:17
Hi Seung,

As a test, could you try wrapping your on_request handler in a try/catch
and see whether any exception is being thrown whilst processing a message.

Or try running against git:master.

Thanks

Will

**Comment by sulsj** [comment] 2015-05-07 21:27
Hi Will

Thanks for the comment. I'm running with git:master. I've tried to catch any exception following your advice and found the below. Any help will be appreciated.

Best,
Seung



--- 
2015-05-07 13:16:37,861 | tfmq-worker | on_request | CRITICAL : Something wrong in on_request(): Socket connection lost
Traceback (most recent call last):
  File "/.../tfmq-worker", line 557, in <module>

  File "/.../tfmq-worker", line 547, in main
    ch.basic_qos(prefetch_count=1) 
  File "build/bdist.linux-x86_64/egg/pika/adapters/blocking_connection.py", line 990, in start_consuming
  File "build/bdist.linux-x86_64/egg/pika/adapters/blocking_connection.py", line 242, in process_data_events
  File "build/bdist.linux-x86_64/egg/pika/adapters/blocking_connection.py", line 358, in _handle_read
  File "build/bdist.linux-x86_64/egg/pika/adapters/base_connection.py", line 356, in _handle_read
AttributeError: 'NoneType' object has no attribute 'recv'

**Comment by vitaly-krugl** [comment] 2015-05-07 21:53
NoneType would be from `data = self.socket.recv(self._buffer_size)` in `_handle_read`. `self.socket` gets set to None when the connection is closed.

@sulsj, the best way to get help is to write a small, simple program that reproduces your failure and post it here. Also, please wrap your code snippets and tracebacks in github markdown for code: 3 back-ticks before and 3 back-ticks after.

` ` `
def foo():
    do_stuff()
    . . .
` ` `

Make sure there are no spaces between the back-ticks.

Also, does your code work okay against pika master? Please post the results of that, too.

Finally, is your app sharing the same pika connection among multiple threads?

**Comment by wjps** [comment] 2015-05-08 08:50
Based on the line numbers that looks like it's against master.

A test case would be idea, failing that a bit more of the logs with pika
logging at debug might prove useful.

**Comment by sulsj** [comment] 2015-05-11 17:06
Thanks for the comment, @vitaly-krugl @wjps 

I'll try to make a test code to reproduce it.

Yes, I'm running it against master.

There are multiple threads but no connection is shared. There is a single client which disperse tasks to many workers via a pika connection. Each pair of client and worker has two threads for heartbeating and housekeeping and both threads have their own pika connections.

If I have 10,000 tasks to process and two workers are created, everything goes fine until around 1500~2000 tasks are completed. After that I lost the connection like the traceback. I might need to set the "heartbeat_interval" or "socket_timeout" in my URLParam.

I'm testing more now. I'll keep you updated. 

Thanks, 
Seung

**Comment by vitaly-krugl** [comment] 2015-05-11 17:59
@sulsj, I ran this simple script successfully on both Mac OS X and Fedora Linux using the latest pika master and Rabbit 3.5.1. I am posting the script here in case it may be of any help:

```
import sys

import pika

MAX_MESSAGES = 10000

def main():
    conn = pika.BlockingConnection()
    channel = conn.channel()

    channel.queue_declare(queue='hello', auto_delete=True)

    def on_incoming(channel, method, in_props, body):
        corr_id = int(in_props.correlation_id)
        print >> sys.stderr, ".",

        channel.basic_ack(delivery_tag=method.delivery_tag)

        if corr_id >= MAX_MESSAGES:
            channel.stop_consuming()

        props = pika.BasicProperties(correlation_id=str(corr_id + 1))
        channel.basic_publish(exchange='',
                              routing_key=method.routing_key,
                              properties=props,
                              body=body)

    consumer_tag = channel.basic_consume(on_incoming,
                                         queue='hello',
                                         no_ack=False)

    # Kickstart by publishing a single message
    channel.basic_publish(
        exchange='',
        routing_key='hello',
        properties=pika.BasicProperties(correlation_id=str(1)),
        body='Hello World!')

    print >> sys.stderr, "start_consuming()"
    channel.start_consuming()
    
    channel.close()


if __name__ == "__main__":
    main()
```

**Comment by sulsj** [comment] 2015-05-12 00:31
Once a blocking connection is opened, what could be the best way to prevent it from closing. I've found I lost the socket connection when a long running worker finally completes and tries to send the result back to the client using the connection from which it received its task.

For your example above, what if 

```print >> sys.stderr, ".",```

takes an hour to complete? 

Thanks, 
Seung

**Comment by vitaly-krugl** [comment] 2015-05-12 00:53
@sulsj, BlockingConnection won't do any hearbeat processing on its own, since it doesn't have its own thread of execution. Its I/O loop runs only when you make a call that requires I/O. I believe that the recommended way to keep things alive is to make periodic calls to the connection's `process_data_events()` method (see http://pika.readthedocs.org/en/latest/modules/adapters/blocking.html).

That said, your app needs to be prepared to deal with connection loss. I am not aware of any 100% effective method to keep the connection alive with any client. And even if it's not the client, then it could be the server that gets restarted, causing connections to be dropped.

**Comment by vitaly-krugl** [comment] 2015-05-12 00:55
https://github.com/gmr/rabbitpy could be a better option for your use case, since it uses a background thread for I/O. I don't have firsthand experience with rabbitpy, though.

**Comment by sulsj** [comment] 2015-05-12 17:43
@vitaly-krugl Thank you for your help and info. 

Best, 
Seung

**Comment by vitaly-krugl** [comment] 2015-05-12 18:45
@sulsj, it sounds like your issue was related to RabbitMQ dropping connections because your workers were busy for a long time and the server's heartbeats were not being serviced. If that's the case, would you mind closing this issue?

**Comment by sulsj** [comment] 2015-05-12 19:26
@vitaly-krugl Nop. Please close this. Thanks a lot again.

**Closed** 2015-05-12 23:38 UTC

**Comment by vitaly-krugl** [comment] 2018-02-17 10:36
UPDATE: `add_callback_threadsafe()` in pull request #956 might help with this. See [this example](https://github.com/vitaly-krugl/pika/blob/2c2b2e6efd45ac26ccc00bf0bb2874efe4cabbce/pika/adapters/asyncio_connection.py#L55-L62). With this feature, you can offload the lengthy processing of your message to another thread, which would then delegate `channel.basic_ack()` to your BlockingConnection thread via `BlockingConnection.add_callback_threadsafe()`, assuming your BlockingConnection is being serviced via `BlockingConnection.sleep()`, `BlockingConnection.process_data_events`, `BlockingChannel.consume()`, `BlockingChannel.start_consuming()`, or similar.
