### ISSUE TITLE
python3.3?

### ISSUE THREAD

**Issue by erlangMike** [pika/pika#369] opened 2013-06-27 08:33 UTC
when support python3.3+?
that is a good idea
Thanks

**Comment by poncki** [comment] 2015-03-20 11:48
Any news about python3 compatibility?

**Comment by opyate** [comment] 2015-04-17 10:39
@gmr 

> There is interest and a roadmap to get there. The pika-python3 port doesn't follow the same direction of pulling out the core AMQP marshaling and demarshaling and moving it to the pamqp library (https://github.com/gmr/pamqp).

Just checking if there's a pika branch which uses pamqp which we can contribute to, or if pamqp is somehow meant to replace pika in another way?

**Comment by ztane** [comment] 2015-04-23 10:52
what exactly there is that is so difficult to make Python 2.6+/Python 3.4 polyglot?

**Comment by opyate** [comment] 2015-04-23 11:00
@ztane from my understanding, nothing if the presumed upgrade path is a brute-force conversion (which it is not -- see @gmr's comment).

**Comment by ztane** [comment] 2015-04-23 13:20
This is exactly the same kind of bs that kept boto from supporting Python 3, as "botocore and boto 3 would come *really soon now*.

**Comment by hayd** [comment] 2015-04-23 16:02
Since Python 2.5 is no longer supported, (exception) syntax is not a problem i.e. you can rewrite to py2 and 3 compatible code. My suggestion would be:

1. run futurize stage 1, and fix up imports etc. to work for python 2 and 3.
2. add python 3.3, 3.4 as allowable failures to travis. (commit to master)
3. get the tests passing on python 3. (hardest part, may take a while, no need to be done singlehanded)

Personally I'm happy to help/PR on the first two points... if it was likely work in this direction would be accepted. Then things can get started.

"When it's done" means never unless there's a plan which can be worked towards/tests that can be chipped away at. At the moment it seems there isn't a plan ?

(#312 was rejected, though to be fair, I think this broke py2...)

**Comment by ztane** [comment] 2015-04-24 05:18
I am almost done with part 3 for the git tip (took 3 hours) there was really no futurize needed, yet there is still some confusion with

a) how `long` is handled,
b) how the field names are actually supposed to be handled

I made a compat module for the case a) and added a `class long(int)` so that the code can deduce whenever to use `long` serialization and whenever to use `int` serialization; for the case b) the thing is that it is not very clear from especially the tests which strings are supposed to genuinely be `bytes` and which should be text; the pitfall here is that some bytestrings are used as dictionary keys etc, and these would not be matched with Python 3 `str` (whereas they'd work as is with python 2 unicode/str if they just were ascii).

As for breaking Py2, every single test is still happily passing on Py 2.7 (and presumably 2.6, as changes were also 2.6 compatible, though I didn't test them yet). I will upload my branch shortly to Github.

**Comment by ztane** [comment] 2015-04-24 05:23
The truth is I do not really know anything about AMQP, so I am not even sure if the `int`/`long` distinction needs to be there; e.g. **must** some numbers even how small then encoded into `'l'` and not `'I'`, or **only those which do not fit in 4 bytes**; I assumed the former, based on how the test and serialization code was written, but if the latter is the case, the code could be streamlined a bit.

**Comment by Conan-Kudo** [comment] 2015-04-28 21:22
@ztane Have you published your code yet?

**Comment by gmr** [comment] 2015-04-29 00:55
@ztane The biggest issue has to deal with Unicode/str/bytes handling and it's not a trivial issue. AMQP specifically calls for UTF-8 in some areas and not others. Handling both properly in Python 2 and 3 while trying to keep backwards compatibility for the average user is not trivial.

This is a solved issue in https://github.com/gmr/pamqp and the plan is to migrate the underpinnings of pika to use it for frame marshaling and unmarshmaling.

Meanwhile there are other core issues such as BlockingConnection that need to be addressed in unison.

The desire for Python 3 support is not lost on me, and is something that I too want to address, but won't likely happen for another few months given my current schedule and obligations.

**Comment by ztane** [comment] 2015-05-01 19:58
the problem is there is still some unicode/bytes confusion in the code, it is outputting some "b''" stuff in acceptance tests

**Comment by ztane** [comment] 2015-05-05 07:05
@Conan-Kudo [published here](https://github.com/ztane/pika), we have now 3 devs sorting out the remaining issues - the issues really are only about "this should be byte data" vs "this should be text data", because pika seems to throw them both very carelessly and encoding something as needed to one or another.

**Comment by ztane** [comment] 2015-05-05 17:34
[A pull request is now available](https://github.com/pika/pika/pull/560)

**Comment by ztane** [comment] 2015-05-13 14:22
[Pull request for the new flat patch](https://github.com/pika/pika/pull/569), the changes are quite nicely viewable at [the GitHub Pull request *files changed* tab](https://github.com/pika/pika/pull/569/files)

**Comment by bkjones** [comment] 2015-05-18 18:39
These changes look refreshingly boring - thanks @zlane 
I have obligations of my own, but I can try really hard to put this changeset through its paces over the next week or so. Of course, if someone else got to it sooner, all the better :)

**Comment by robertlagrant** [comment] 2015-06-02 08:00
@ztane thanks for cleaning up the code _and_ converting it! @bkjones have you had a chance to test?

**Comment by hayd** [comment] 2015-06-02 08:17
@robertlagrant It's merged in #581, so this issue can be closed now?

**Comment by robertlagrant** [comment] 2015-06-02 08:38
@hayd okay, that's cool. Just saw that pika was still Python 2-only on Pypi, so I thought it wasn't finalised.

**Comment by flying-sheep** [comment] 2015-06-04 17:52
yeah, updating PyPI seems to be the only thing left yay!

**Comment by gmr** [comment] 2015-06-04 22:55
Not quite, but close. There's an issue that is illustrated in the unit tests by a change I recently made where instead of logging an error condition that should never happen, it raises an exception.

Said error condition is happening in all adapters it appears, so we need to trace down *how* it's happening and get it fixed before I release 0.10.

**Comment by Conan-Kudo** [comment] 2015-07-01 16:43
@gmr Is there an issue where this is being tracked?

**Comment by gmr** [comment] 2015-07-01 17:03
I believe at this point it's resolved and we're just waiting for 0.10 to stabilize enough for a pre-release to be pushed to pypi.

**Comment by vitaly-krugl** [comment] 2016-02-27 21:35
Presently passing tests on Python 3.3, 3.4, and 3.5.

**Closed by vitaly-krugl** 2016-02-27 21:35 UTC
