### ISSUE TITLE
pika.exceptions.IncompatibleProtocolError

### ISSUE THREAD

**Issue by AdamMiltonBarker** [pika/pika#741] opened 2016-04-22 23:49 UTC
Hi I am attempting to get connected from an RPI3 to a fresh install of RabbitMQ that is hosted on subdomain on my Centos VPS. I can easily connect to the management site but cannot get a channel open. The code is below and error message below that.

```
import pika
import sys

host = "DOMAINONVPS"
username = "USERNAME"
password  =  "PASSWORD"
port = 5671
locationId = "1"
deviceId = "1"

credentials = pika.PlainCredentials(username, password)
params  =  pika.ConnectionParameters(host, port, locationId, credentials,socket_timeout=10)
connection = pika.BlockingConnection(params)
channel = connection.channel()
```

Error log:

```
sudo python RaspberryPiAMQPApplication.py
Traceback (most recent call last):
  File "RaspberryPiAMQPApplication.py", line 13, in <module>
    connection = pika.BlockingConnection(params)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 339, in __init__
    self._process_io_for_connection_setup()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 374, in _process_io_for_connection_setup
    self._open_error_result.is_ready)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 410, in _flush_output
    self._impl.ioloop.poll()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/select_connection.py", line 602, in poll
    self._process_fd_events(fd_event_map, write_only)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/select_connection.py", line 443, in _process_fd_events
    handler(fileno, events, write_only=write_only)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 364, in _handle_events
    self._handle_read()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 407, in _handle_read
    return self._handle_error(error)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 338, in _handle_error
    self._handle_disconnect()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 288, in _handle_disconnect
    self._adapter_disconnect()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/select_connection.py", line 95, in _adapter_disconnect
    super(SelectConnection, self)._adapter_disconnect()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 154, in _adapter_disconnect
    self._check_state_on_disconnect()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 169, in _check_state_on_disconnect
    raise exceptions.IncompatibleProtocolError
pika.exceptions.IncompatibleProtocolError
```

Any ideas please, there are no logs of attempts to connect on the server which is strange, it is definitely the correct address.

**Comment by vitaly-krugl** [comment] 2016-04-23 02:27
@AdamMiltonBarker, which version of pika are you using?

The fact that you're getting `IncompatibleProtocolError` exception, suggests that socket connection actually succeeded, but then the connection got dropped for some reason. Have you checked RabbitMQ logs? Also, WireShark is an amazing tool for network analysis. The recent versions of WireShark have support of AMQP protocol (use amqp as Display Filter).

To get more logs out of pika, run something like this before instantiating BlockingConnection:

```
import logging

logging.basicConfig(level=logging.DEBUG)
```

**Comment by AdamMiltonBarker** [comment] 2016-04-23 02:33
Thanks for the reply there are no errors in the logs as if it never made it to the broker. I have written a more detailed description here:

https://groups.google.com/forum/#!topic/rabbitmq-users/u9hpB1ewDjQ

**Comment by vitaly-krugl** [comment] 2016-04-23 03:40
@AdamMiltonBarker, I suspect that there is a connectivity issue; for example, the incorrect use of the RabbitMQ SSL port 5671 in your example to reproduce the problem (instead of 5672).

If you really intended to use SSL to connect to RabbitMQ, then you would need to configure the additional SSL settings in `pika.ConnectionParameters`. However, I suspect that SSL support might be broken in pika at the moment (there are several ssl-related issues posted about it in this repo).

**Comment by vitaly-krugl** [comment] 2016-04-23 22:27
You can verify TLS connectivity to rabbitmq without pika first: `openssl s_client -connect 127.0.0.1:5671 -tls1`, assuming that the broker is running on the same machine, or use different address if on a different machine. This should connect with a recent rabbitmq broker configured with default SSL version options. If this doesn't work, then I wouldn't expect it to work with pika either, and you need to solve your rabbitmq configuration and networking first.

I followed the setup instructions in https://www.rabbitmq.com/ssl.html, including rabbitmq.config and generation of all the certificates, and was able to get it to work with pika.BlockingConnection, after all.

Both the client and rabbitmq server were running on my MacBookPro. I created rabbitmq.config in its default location for OS X: /usr/local/etc/rabbitmq/rabbitmq.config

Its contents (using certificate directory structure and contents created following instructions in https://www.rabbitmq.com/ssl.html):

Note that in my test, I configured rabbit to accept SSL connection only on the local interface.

```
[
  {rabbit,
    [   
      {ssl_listeners, [{"127.0.0.1", 5671}]},

      %% Configuring SSL.
      %% See http://www.rabbitmq.com/ssl.html for full documentation.
      %%
      {ssl_options, [{cacertfile,           "/Users/me/rabbitmqcert/testca/cacert.pem"},
                     {certfile,             "/Users/me/rabbitmqcert/server/cert.pem"},
                     {keyfile,              "/Users/me/rabbitmqcert/server/key.pem"},
                     {verify,               verify_peer},
                     {fail_if_no_peer_cert, false}]}
    ]   
  }
].
```

After creating the rabbitmq.config file, I restarted the rabbitmq broker. I used `rabbitmq-server` (without the -detached arg) to start it back up and verify that it started successfully.

The following pika commands worked for me:

```
import ssl
import pika

cp = pika.ConnectionParameters(ssl=True, ssl_options=dict(ssl_version=ssl.PROTOCOL_TLSv1))
conn = pika.BlockingConnection(cp)

ch = conn.channel()

ch.queue_declare("sslq")
ch.publish("", "sslq", "abc")
```

**Comment by vitaly-krugl** [comment] 2016-04-24 00:11
And here is a more sophisticated example that forces mutual cert verification: https://github.com/pika/pika/issues/726#issuecomment-213853787

**Comment by vitaly-krugl** [comment] 2016-04-24 17:26
@AdamMiltonBarker, PR #742 contains examples of TLS connectivity using mutual and server-only certification authentication. I verified those on OS X, in addition to all the info in my previous comments.

At this point, your post at https://groups.google.com/forum/#!topic/rabbitmq-users/u9hpB1ewDjQ should be more productive. I am going to close this issue for now.

**Closed by vitaly-krugl** 2016-04-24 17:26 UTC

**Comment by AdamMiltonBarker** [comment] 2016-04-30 00:04
Ok thank you checking this all out again tonight.
