### ISSUE TITLE
Allow publishing of big messages to RabbitMQ

### ISSUE THREAD

**Issue by mlmarius** [pika/pika#831] opened 2017-06-30 16:30 UTC
I get an error when trying to publish messages above a specified size using the AsyncPublisher example. Digging around I found something in the spec file:

FRAME_MAX_SIZE = 131072

From what I gather I understand that RabbitMQ itself is able to deal with huge files in the hundreds of MB. How can I tune things so that I am able to send a 50MB file into RabbitMQ? I see that there is a tune callback. Can that be used to increase the frame size? An example? Thanks!

This is the debug output when trying to publish stuff larger than the FRAME_MAX_SIZE:

2017-06-30 19:18:01,501 DEBUG      PUBLISHER                      schedule_next_message                655 : Scheduling next message for 0.0 seconds
2017-06-30 19:18:01,503 INFO       pika.connection                _on_terminate                        1891: Disconnected from RabbitMQ at 127.0.0.1:5672 (501): FRAME_ERROR - type 2, all octets = <<>>: {frame_too_large,150081,131064}
2017-06-30 19:18:01,503 WARNING    PUBLISHER                      on_channel_closed                    532 : Channel was closed: (501) FRAME_ERROR - type 2, all octets = <<>>: {frame_too_large,150081,131064}
2017-06-30 19:18:01,503 WARNING    pika.connection                close                                1135: Suppressing close request on <SelectConnection CLOSED socket=None params=<URLParameters host=127.0.0.1 port=5672 virtual_host=/ ssl=False>>
2017-06-30 19:18:01,504 WARNING    PUBLISHER                      on_connection_closed                 483 : Connection closed, reopening in 5 seconds: (501) FRAME_ERROR - type 2, all octets = <<>>: {frame_too_large,150081,131064}

**Comment by vitaly-krugl** [comment] 2017-06-30 19:01
@mlmarius: FRAME_MAX_SIZE determines the max frame size. Each message that's larger than this is divided into multiple frames. The total message size is limited by available memory (client/server) and also possibly disk size (server).

Which pika version are you using and on which platform? Which version of RabbitMQ server?

Please provide a short, self-contained snippet of code that reproduces your issue.

I had no problem executing the following snippet of code using pika 0.10.0 on OS X. It's using BlockingConnection, which builds on top of SelectConnection:

```
c = BlockingConnection()
ch = c.channel()
ch.publish("", "", "a" * 100000000, properties=None, mandatory=False, immediate=False)
```

**Comment by vitaly-krugl** [comment] 2017-06-30 19:04
Is your app using more than one thread, by chance?

**Comment by mlmarius** [comment] 2017-06-30 20:21
Yes, app is using more than one thread. It is using one thread for the publisher and one for the consumer, each with it's own connection. But I think I may have stumbled upon what was wrong with my app. For my publisher i was using the example from here: https://github.com/pika/pika/pull/710/files

In that publisher example the publish is performed like so:

``
properties = pika.BasicProperties(app_id='example-publisher',
                                          content_type='application/json',
                                          headers=message)

        self._channel.basic_publish(self.EXCHANGE, self.ROUTING_KEY,
                                    json.dumps(message, ensure_ascii=False),
                                    properties)
        self._message_number += 1
        self._deliveries.append(self._message_number)
        LOGGER.info('Published message # %i', self._message_number)
        self.schedule_next_message()
``

I think the problem is in the example, here: 

``properties = pika.BasicProperties(app_id='example-publisher',
                                          content_type='application/json',
                                          headers=message)
``
I think headers=message makes the thread die when I attempt to publish big messages. After removing the heades=message part the publisher works as expected, I can publish big messages to RabbitMQ and the thread is not killed anymore.

**Comment by vitaly-krugl** [comment] 2017-06-30 20:46
Good job figuring this out @mlmarius ! The original example should have used different variables/values for the property headers versus the message data to make it less error-prone.

Also, pika could probably do a better job validating the size of the header before trying to send it out.

I just opened issue #832 to make the async publisher example less error-prone. It's a simple change that would help the next developer avoid this mistake. Would you like to tackle it?

And I am going to close this issue since you have it resolved.

**Closed by vitaly-krugl** 2017-06-30 20:46 UTC
